### ISSUE TITLE
Abide: equalTo not working as expected in some edge cases

### ISSUE THREAD

**Issue by ruben-santacruz** [zurb/foundation#4820]
I've found a case when the equalTo validator doesn't work as expected.

* Go to http://codepen.io/ruben-santacruz/pen/qvlLf where I've prepared a little example form.
* Enter *abc* in the **Enter new password** field.
* Enter *abcd* in the **Confirm password** field.
* Go back to the **Enter new password** field and add a *d* so it is *abcd* now.
* Now the two fields are equal, but the **Confirm password** field still shows an error. To remove it you have to force the check again, bringing the focus to the **Confirm password** field and leaving it or clicking **Submit**.

I know it is a little weird case but I think it should be fixed. What do you think?

**Comment by gakimball** [comment]
In Foundation 5.5 this issue still persists, but note that if you tab to the second password field, and then tab away from it, the error goes away.

I think it's because Abide is only checking to see if the fields match when checking the *second* password field, because it's the one with the `data-equalto` attribute. So the validation doesn't go two ways, basically.

So given the following code:

```html
<input type="text" required pattern="alpha_numeric" id="password"> 
<input type="text" required pattern="alpha_numeric" id="password-confirm" data-equalto="password">
```

Right now a validator is added to `#password-confirm` to check for equality. But *another* validator should be added to `#password` to check in the other direction.

**Comment by rafibomb** [comment]
We added this to our "known issues" section in our planning board for the next version. A PR would be valuable to the community, otherwise It will be addressed then. You can see and vote on the proposed updates here: https://trello.com/b/QBPKlQqf/foundation-sites
