### ISSUE TITLE
Reveal options not working 5.2.1 on open/close events

### ISSUE THREAD

**Issue by focusedonfit** [zurb/foundation#4832]
The code below worked in V4 but upon updating to 5.2.1 it no longer works. No errors in console, just ignores options.

$('#myModal').foundation('reveal', 'close', {animation: 'fade',animation_speed: 1000});

**Comment by jeaniec** [comment]
I'm closing this as a non-issue because the options that were initially discussed were meant to be passed in at initialization. We'll take into consideration programmatically being able to update these options for the next release of Foundation as I can see the desire in wanting to change these variables as you go.
