### ISSUE TITLE
Abide trigger issue

### ISSUE THREAD

**Issue by ekkl** [zurb/foundation#4945]
For fields ``<input type="password" data-equato="someid" name="confpass">``
Trigger on don't work
``$('input').on('valid' function(){
console.log('valid: ' + $(this).attr('name'));
});``
Any messages about valid this input.
I can show this on Codepen page

**Comment by rafibomb** [comment]
Looks like this issue has been reported before 
https://github.com/zurb/foundation/issues/4820
zurb/foundation: #4730

We added this to our "known issues" section in our planning board for the next version. A PR would be valuable to the community, otherwise It will be addressed then. You can see and vote on the proposed updates here: https://trello.com/b/QBPKlQqf/foundation-sites
