### ISSUE TITLE
.foundation('slider', 'set_value', n) triggers change event for all range sliders

### ISSUE THREAD

**Issue by leafymind** [zurb/foundation#4959]
When you add an global change event for all range sliders:
```javascript
$('[data-slider]').on('change', function()
{
    console.log(this, 'has changed!');
    $(this).css('background-color', 'red');
});
```

... and set the value of an explicit range slider:
```javascript
$('[data-slider]').eq(1).foundation('slider', 'set_value', 0);
```

the change-event for all range sliders will be triggered.

**Comment by gakimball** [comment]
Looking at the CodePen, you can see that both range sliders immediately turn red, because the act of setting the initial value for the slider triggers the `change` event. However, when I drag the slider, I only see `console.log()`s for the one I'm dragging.

Is the issue, then, that the `change` event is being fired right when the slider is first initialized? We could change it to prevent the event from firing the first time the UI is set.

**Comment by rafibomb** [comment]
This is a very specific change you're looking for. I think it would be ok to prevent the event from firing when the slider is initialized. 

A PR would be awesome for this, we'll add it in. We'll close this here for now and keep it in mind for the next version which we are working on.
