### ISSUE TITLE
data-abide-validator erroring when multiple functions defined

### ISSUE THREAD

**Issue by Saturn2888** [zurb/foundation#5102]
If I do something like this: `data-abide-validator="checkPattern invalidMessage"`, I will get this JavaScript error: `Uncaught TypeError: Cannot read property 'apply' of undefined`.

Can we parse the contents of data-abide-validator as an array?

**Comment by rafibomb** [comment]
There's been a lot of changes to Abide since this post and it's likely been solved. https://github.com/zurb/foundation/commits/master/js/foundation/foundation.abide.js

You can see our planning board for the next version and vote on the proposed updates here: https://trello.com/b/QBPKlQqf/foundation-sites

**Comment by Saturn2888** [comment]
Thanks for your response. I haven't messed with this in a long time so I can no longer confirm. I agree, chances are it's fixed.
