### ISSUE TITLE
Abide input type time

### ISSUE THREAD

**Issue by adamk33n3r** [zurb/foundation#5106]
Using the input type of time is interfering. Abide makes it so you can put the validations in your type attribute. This causes problems because there is a legitimate time type as well as a time pattern. Abide will always invalidate the time input when all three sections are set e.g. hh:mm am/pm. This makes it impossible to use Abide if you have a time input.

It, for some reason, isn't messing with the input[date]. It won't invalidate that one.

## Steps to reproduce
* Have
```
<form method="get" data-abide>
    <label for="time">Time</label>
    <input id="time" type="time">
    <button type="submit"/>
</form>
```
* Change the time to something like 2:00 PM

**Comment by rafibomb** [comment]
There's been other reports of the date validation not working.

We added this to our "known issues" section in our planning board for the next version. A PR would be valuable to the community, otherwise It will be addressed then. You can see and vote on the proposed updates here: https://trello.com/b/QBPKlQqf/foundation-sites
