### ISSUE TITLE
dropdown: off call may mess up non framework code !

### ISSUE THREAD

**Issue by istrasoft** [zurb/foundation#5495]
in the dropdown JS component, there is a S(this.scope).off('.dropdown') call which may mess up non framework code.

If for example I attach a custom event named 'opened.foo.bar.dropdown' that has something extra when the dropdown opens, then it gets automatically unregistered by that call.

I think the call should be S(this.scope).off('.fndtn.dropdown') instead

**Comment by rafibomb** [comment]
We are making the name spacing consistent across all plugins for the next version coming soon. Related - https://github.com/zurb/foundation/issues/5486

We added this to our "known issues" section in our planning board for the next version. A PR would be valuable to the community, otherwise It will be addressed then. You can see and vote on the proposed updates here: https://trello.com/b/QBPKlQqf/foundation-sites
