### ISSUE TITLE
Clearing broken on Android and Windows Phone 8

### ISSUE THREAD

**Issue by JordanWirth** [zurb/foundation#5541]
clearing broken on 2.3.5

**Comment by rafibomb** [comment]
The problem is actually related to the fact that modernizr doesn't see Windows devices as a touch device. There might be some hack to get around this but not a viable solution for a professional framework.

See: https://github.com/Modernizr/Modernizr/issues/1179
and https://github.com/Modernizr/Modernizr/issues/448

**Comment by rafibomb** [comment]
Related - https://github.com/zurb/foundation/issues/4346

We added this to our "known issues" section in our planning board for the next version. A PR would be valuable to the community, otherwise It will be addressed then. You can see and vote on the proposed updates here: https://trello.com/b/QBPKlQqf/foundation-sites
