### ISSUE TITLE
Feature request: add aria attribute to javascript components like tabs, accordion

### ISSUE THREAD

**Issue by erredeco** [zurb/foundation#5686]
Javascript components like tabs, accordion could be improved adding aria attributes like
aria-selected, aria-expanded, aria-hidden... (of course they must be updated via Javascript)

see for example jqueryUI components

**Comment by rafibomb** [comment]
The next version will be built from the ground up with accessibility in mind. You can see it in our planning board for the next version. A PR would be valuable to the community, otherwise It will be addressed then. You can see and vote on the proposed updates here: https://trello.com/b/QBPKlQqf/foundation-sites
