### ISSUE TITLE
Javascript: TypeError: ":".split is not a function

### ISSUE THREAD

**Issue by jtouza** [zurb/foundation#5704]
Error on foundation.js:503 (Foundation.utils.data_options) version 5.3.3 and 5.4
Fails when a param on data-options attribute is a float

Example:

```
<div data-options="lat:20.662012;lng:-103.400553;"></div>
```

This is the line:
```
opts_arr = (cached_options || ':').split(';');
```

the solution, add toString() method:

```
opts_arr = (cached_options || ':').toString().split(';');
```

I'm not sure to pull this change. would be my first commit on foundation repo :)

**Comment by jeaniec** [comment]
@jtouza I'm not sure that this issue is coming from the utils object. I think it might be a problem with whatever component you're using it with. It looks like that since this issue was reported, there is a way of sanitizing options after the options have been passed through.

Closing this issue for now.
