### ISSUE TITLE
Reveal open when existing modal is open fails

### ISSUE THREAD

**Issue by jbafford** [zurb/foundation#5721]
Since 1c966e7, opening a reveal modal when an existing modal is open fails with the error:
    ``TypeError: undefined is not an object (evaluating 'target.attr')``

The problem line of code in foundation.reveal.js is:
159: ``if (modal.hasClass('open') && target.attr('data-reveal-id') == modal.attr('id')) {``

When triggered with ``$someContainer.foundation('reveal', 'open')``, ``target`` is undefined, causing that line of code to fail.

**Comment by MartijnR** [comment]
When instantiating the reveal with options, the target becomes indeed the options object as @sveetch commented. E.g.

```js
$dialog.foundation( 'reveal', 'open', {
    animation: 'none'
} );
```
Otherwise target is always undefined for me.

With an options object the error is:  `Uncaught TypeError: undefined is not a function` (because the target has no attr() method...)

Without an options object the target is undefined so the error is: ` Uncaught TypeError: Cannot read property 'attr' of undefined`

What seems pretty clear when looking at the code is that `target` [can be falsy] (https://github.com/zurb/foundation/blob/master/js/foundation/foundation.reveal.js#L140)

Without setting a value for target an attempt is made, [a few lines further](https://github.com/zurb/foundation/blob/master/js/foundation/foundation.reveal.js#L157), to read an attribute of this falsy target if the modal is open.

So if target **can indeed be falsy**, this is a bug.

I pasted the complete code below with 2 comments.

```js
      if (target) {
        if (typeof target.selector !== 'undefined') {
          // Find the named node; only use the first one found, since the rest of the code assumes there's only one node
          modal = self.S('#' + target.data(self.data_attr('reveal-id'))).first();
        } else {
          modal = self.S(this.scope);

          ajax_settings = target;
        }
      } else {
        // ** TARGET IS FALSY AND REMAINS SO  *
        modal = self.S(this.scope);
      }

      var settings = modal.data(self.attr_name(true) + '-init');
      settings = settings || this.settings;

      // AN ATTEMPT IS MADE TO READ THE ATTRIBUTE OF FALSY TARGET IF MODAL IS OPEN
      if (modal.hasClass('open') && target.attr('data-reveal-id') == modal.attr('id')) {
        return self.close(modal);
      }
```

**Comment by jasonlfunk** [comment]
I ran into this today as well. +1

**Comment by rubyjedi** [comment]
+1, please, I am also running into this.

**Comment by elbarsal** [comment]
Much simpler workaround for now (haven't tested thoroughly yet though).

$("#ContentModal").removeClass("open");

This will short circuit the if statement causing the problem - but it won't close the modal, so you'll have to close and refill it yourself.

**Comment by jeaniec** [comment]
There is a recent pull request that I think will solve this issue. https://github.com/zurb/foundation/commit/586fcb24779ac82bab22e178428b15b9b3dd256a

**Comment by htmlauthor** [comment]
Hi Guys,
I believe this bug is still not resolved. Please take a look at my simple example: http://www.kabasinskas.lt/stuff/Reveal_test/ you will see JS error after clicking on link inside first reveal window.

**Comment by FineLineAutomation** [comment]
It is an issue. You can fix it by changing the reference of this to self. See https://gist.github.com/FineLineAutomation/e1c06142e5afaa98cfba#file-foundation-reveal-js-L210-L212 for the lines I changed.

**Comment by htmlauthor** [comment]
@FineLineAutomation I am using foundation version from github in my example.

if you would look at foundation.reveal.js file in my example, you would see these lines in place: http://www.kabasinskas.lt/stuff/Reveal_test/foundation/js/foundation/foundation.reveal.js

Still even with these lines, issue does exist.

**Comment by mikejoyceio** [comment]
Also running into this issue.

**Comment by htmlauthor** [comment]
+1

**Comment by htmlauthor** [comment]
still an issue...

**Comment by macrojames** [comment]
Also ran into this lately on 5.5.2

**Comment by a-vakulenko** [comment]
+1

**Comment by ibroadfo** [comment]
i think this is fixed in #6517

**Comment by numediaweb** [comment]
I still have it;
```
if (modal.hasClass('open') && target.attr('data-reveal-id') == modal.attr('id')) {
        return self.close(modal);
      }
```
Uncaught TypeError: Cannot read property 'attr' of undefined

**Comment by aalpar** [comment]
+1

**Comment by pide2000** [comment]
I still have it too
