### ISSUE TITLE
image interchange is not working if default image set at last

### ISSUE THREAD

**Issue by vanilla-thunder** [zurb/foundation#5786]
its not mentioned in the documentation, that default values should come first, so i guess it should work if the default value is the last one, too.

jsfiddle: http://jsfiddle.net/t6uh75wz/

**Comment by rafibomb** [comment]
Makes sense that this should work in any order but the docs examples all have default first. I added this not to the docs for now and...

We added this to our "known issues" section in our planning board for the next version. A PR would be valuable to the community, otherwise It will be addressed then. You can see and vote on the proposed updates here: https://trello.com/b/QBPKlQqf/foundation-sites
