### ISSUE TITLE
Incorrect column widths

### ISSUE THREAD

**Issue by brightonmike** [zurb/foundation#5930]
Hello.

I've been scratching my head over a particular issue with a new website using Foundation 5 for quite some time. On this page you will see there are various white lines in the grid and images do not occupy the correct widths and heights. This leads to an ever so slightly disjointed layout.

It seems petty, but for us pixel perfectionists, this is a problem.

http://testbench.watb.co.uk/watbnew/

Please see this image if you're not seeing the issue: https://dl.dropboxusercontent.com/u/20205486/f5-grid.JPG

I'm using the libsass setup. The only thing I have changed is the max-width of the row - but this issue persists even when that is left at the default.

It effectively means you cannot achieve these layouts, with Foundation, without these thin lines. If you had a long page, this could end up with a messed up layer.

The issue lies with how the widths are calculated. If you look at the columns, they are calculated as follows:

`.medium-4 {
width: 33.33333%;
}`

If you manually change that value to the following in devtools, the issue is resolved:

`.medium-4 {
width: 33.33334%;
}`

Heck - I know this is a bit of a silly issue. But for me it's important. I apologise if this turns out not to be an issue with Foundation, but I can't currently see how it's not as the only way I can fix it currently is to manually specify the column width as an override.

**Comment by rafibomb** [comment]
This has been a long standing issue with responsive. There hasn't been a great Sass solution or otherwise that we can add to the framework. We're going to keep this in our known issues tracker and continue looking for better solutions. 

We added this to our "known issues" section in our planning board for the next version. You can see and vote on the proposed updates here: https://trello.com/b/QBPKlQqf/foundation-sites
