### ISSUE TITLE
Offcanvas multilevel  open current level

### ISSUE THREAD

**Issue by grigno** [zurb/foundation#6006]
It would be nice to open the menu in the current node.

**Comment by rafibomb** [comment]
Thanks for added detail. The multi level off-canvas does not have an event handler for this. In the next version which we are working on now, we'll have better event handling for this. 

You can remove this line as a work-around.

We added this to our "known issues" section in our planning board for the next version. A PR would be valuable to the community, otherwise It will be addressed then. You can see and vote on the proposed updates here: https://trello.com/b/QBPKlQqf/foundation-sites

**Comment by ejwaibel** [comment]
+1 I am working on a project that needs this functionality as well.
