### ISSUE TITLE
Popover closing delay

### ISSUE THREAD

**Issue by matanster** [zurb/foundation#6156]
The popover directive (without any configuration other than the default) seems to delay before closing but not before opening. It feels rather awkward in terms of the user experience, given it doesn't delay when opening, only when closing. The delay interval is also too long imo for being a good default for closing in terms of user experience when a fade out effect is not used.

Can be seen at http://plnkr.co/edit/LdCOLnBK3itskjTJp037

(Tested on Chrome Version 39.0.2171.95 (64-bit))

This behaviour is probably inherited from the [tooltip directive](http://pineconellc.github.io/angular-foundation/#/tooltip) and the issue applies to both.

**Comment by rafibomb** [comment]
In this version of Foundation, we are only supporting the jQuery components we created. There are angular ports others have made that are not part of Foundation. 

The <a href="http://foundation.zurb.com/forum">Foundation forum</a> would be a great place to seek some help with troubleshooting what might be going on here. If it turns out to be a defect, you'll have some more info to provide here which will help prioritize and get it fixed.

We're trying to keep the issue list focused on confirmed defects in Foundation, so any help everyone can provide to differentiate between usage / troubleshooting and actual defects is appreciated!

**Comment by matanster** [comment]
Good luck

On Thursday, January 8, 2015, Rafi <notifications@github.com> wrote:

> Closed #6156 <https://github.com/zurb/foundation/issues/6156>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zurb/foundation/issues/6156#event-215655252>.
>


-- 
Sent from Gmail Mobile
