### ISSUE TITLE
Javascript in IE9

### ISSUE THREAD

**Issue by sofiaaFa** [zurb/foundation#6167]
Hello 
I create website by using joomla 3 and template shaper_helix but javacript doesn't work for IE9 and it works in IE8
This is website http://babalkhir.com/ help me

**Comment by gakimball** [comment]
Do you see any JavaScript errors in IE9 specifically? What components aren't working?

**Comment by rafibomb** [comment]
The  <a href="http://foundation.zurb.com/forum">Foundation forum</a> would be a great place to seek some help with troubleshooting what might be going on here. If it turns out to be a defect, you'll have some more info to provide here which will help prioritize and get it fixed.

We're trying to keep the issue list focused on confirmed defects in Foundation, so any help everyone can provide to differentiate between usage / troubleshooting and actual defects is appreciated!
