### ISSUE TITLE
Magellan chockes on scrolling

### ISSUE THREAD

**Issue by italomaia** [zurb/foundation#6199]
Using magellan, when scrolling the page down, it chockes for a second, when changing from one destination to another.

**Comment by rafibomb** [comment]
What browser? Can't replicate this on the docs in Chrome.

**Comment by italomaia** [comment]
Firefox

**Comment by gakimball** [comment]
What operating system as well?

**Comment by italomaia** [comment]
Ubuntu 14.04

**Comment by gakimball** [comment]
Are you seeing this in [our documentation](http://foundation.zurb.com/docs/components/magellan.html) or in your own code?

It's also worth noting that if the nav isn't scrolling very far between destinations, the slight ramp-up in the animation speed could maybe be perceived as "choking", because it might look like the animation stutters very slightly while it accelerates, but that's probably not what you're seeing.

**Comment by italomaia** [comment]
See here http://infratec.eco.br/ The choking happens in my code, but it is pretty ordinary.

**Comment by rafibomb** [comment]
We can't replicate this on the docs. Also, once I close the language notification in Chrome, the hesitation stops.

The <a href="http://foundation.zurb.com/forum">Foundation forum</a> would be a great place to seek some help with troubleshooting what might be going on here. If it turns out to be a defect, you'll have some more info to provide here which will help prioritize and get it fixed.

We're trying to keep the issue list focused on confirmed defects in Foundation, so any help everyone can provide to differentiate between usage / troubleshooting and actual defects is appreciated!
