### ISSUE TITLE
_settings.scss uses wrong path to import _functions.scss

### ISSUE THREAD

**Issue by Ludachrispeed** [zurb/foundation#6201]
`foundation/scss/foundation/_settings.scss` has the following line in it:

    @import "foundation/functions";

But that's the wrong path, and it causes an error when compiled with libsass:

    file to import not found or unreadable: foundation/functions

 They are sibling files, so it should just be:

    @import "functions";

**Comment by Ludachrispeed** [comment]
I have this working now. I'm using `gulp` with the `gulp-sass` plugin (which uses `node-sass`, which uses `libsass`). I retrieve foundation using `bower`.

I see that the Gruntfile for foundation sets the loadPath:

    loadPath: [__dirname + '/scss'],

So I guess `_settings.scss` is relying on that `loadPath` to find `_functions.scss`.

FWIW, I get around it by including this in my gulp task:

    .pipe(sass({
        includePaths: ['bower_components/foundation/scss/']
    }))

Still, it might be at least good to document (for bower users) that you need to include that `scss` directory in your load path.

**Comment by doertedev** [comment]
This also fails for compass users. Don't you think it is a good idea to include it separately? Or put the functions in the global component which is being required by almost every other component anyways? I just made a writeup on the _settings.scss issue and came to the conclusion that it would be the best for sass beginners to delete it. 
* [my writeup](http://doertedev.github.io/2015/01/26/sass-and-foundation.html)
* [ZF6-JS discussion](https://github.com/zurb/foundation/issues/6197#issuecomment-71001560)
* [ZF6-SASS discussion which made me think](https://github.com/zurb/foundation/issues/6196#issuecomment-71189733)
Especially the interesting question of how to properly document removed/renamed variables is to be considered. Why even keep it?

**Comment by gakimball** [comment]
@Ludachrispeed We don't currently document a plain Bower install (just a Compass install), but we probably should, in which case we can recommend using the include path `bower_components/foundation/scss`. Our Compass/libsass templates are already configured this way.

@doertedev The issue is that the settings file needs to be imported before *any* framework code, so that the user's overrides are actually set. In Foundation 5 the global component does include some functions, but it also includes CSS output. In the next version of the framework the global file will be streamlined, and the Sass functions will all be moved into their own file. (Some sets of functions that work as mini "libraries" may also get their own files.) Sass implementations also differ in how they look for imports, which is why we explicitly import `foundation/functions` and not just `functions`, as we assume the compiler is starting at our explicitly-defined import path.

I'm not sure I agree with the premise that a new user should outright *remove* the settings file, however. If you aren't trying to modify the structure of a component, and don't intend to create multiple versions of it, modifying the settings variables is the easiest way to change styles. The settings file defines *defaults*, both for the CSS output and the mixins, and there's always going to be a default version of a component.

You're right that it's super annoying to have to update a Foundation settings file, however, so it may be worth writing a script that can intelligently update an existing file.

**Comment by Ludachrispeed** [comment]
@gakimball  Thanks for the clear response! I'll throw in a vote for documentation for a bower install. Let me know if it would be helpful for me to check in a minimal example of my workflow with foundation/bower/gulp.

**Comment by flexbox** [comment]
@doertedev I have a small side project where my solution is 
- include `foundation/functions.scss`
- make my own `_custom-settings.scss` partial based on the `_settings.scss` variables

It works well with all my projects and i can build website faster when i include foundation with bower

https://github.com/flexbox/foundation-boilerplate/blob/master/source/assets/stylesheets/application.scss

**Comment by gakimball** [comment]
Alright, I added a section to our Sass documentation explaining our recommended way of incorporating Foundation into a build system. It includes sample configurations for `grunt-contrib-sass` and `gulp-sass`.

**Comment by christiantype** [comment]
I'm still trying to resolve this issue. I'm getting an error in my browser that says it can't find 

@import 'foundation/functions';

How do I go about solving this? This issue seems to have come out of nowhere.

**Comment by jgacuca567** [comment]
@christiantype could you post your gruntfile.js that might let me know what could be the problem.

**Comment by christiantype** [comment]
@jgacuca567, the problem just solved itself. Don't know how but thanks anyways! 

:)

**Comment by jgacuca567** [comment]
Ok.

**Comment by SalahAdDin** [comment]
What's the way to do this it with Grunt?

**Comment by jgacuca567** [comment]
@SalahAdDin , how have you setup your foundation setup, do mind posting a screenshot, of your setup.

I use grunt, so I was able to figure what was causing the import functions to not show.
