### ISSUE TITLE
attribute min doesn't work with foundation 5.5.0

### ISSUE THREAD

**Issue by gbrthebest** [zurb/foundation#6211]
Hello, I am using the foundation 5.5.0 with abide and angular 1.3.8, trying to make a validation of the min attribute of an input type = number but the foundation ignores this attribute, that is, not set the class "error" in the parent or invalidate the form. Why?

**Comment by rafibomb** [comment]
Good question. Foundation does not have Angular support. You're best off asking on the forum.

The <a href="http://foundation.zurb.com/forum">Foundation forum</a> would be a great place to seek some help with troubleshooting what might be going on here. If it turns out to be a defect, you'll have some more info to provide here which will help prioritize and get it fixed.

We're trying to keep the issue list focused on confirmed defects in Foundation, so any help everyone can provide to differentiate between usage / troubleshooting and actual defects is appreciated!
