### ISSUE TITLE
blockgrids can exceed viewport width

### ISSUE THREAD

**Issue by r3wt** [zurb/foundation#6213]
adding 

`max-width: 100%;`

fixes issue.

**Comment by rafibomb** [comment]
The Mixin is set to width: 100%, can you show us how it's not working as expected? http://codepen.io/rafibomb/pen/EqCdJ

**Comment by r3wt** [comment]
it needs the max-width: 100% for media only screen

**Comment by gakimball** [comment]
The issue is that the block grid is not inside a column. The "rule" of layouts in the framework is that all content needs to be inside a column, and in this case the block grid is technically considered content. Block grids have negative margins, which align the edge of the component with the edge of the grid. If you place a block grid standalone, those negative margins will cause it to break out of its container, creating the overflow you're seeing.

Here's an example with a 100% width row and no overflow: <http://codepen.io/anon/pen/MYmdam>

**Comment by r3wt** [comment]
i have it inside of a column and a row collapse and it still overflows the viewport. in fact, here's the exact code. you can see i used several blockgrids to create a footer. if i remove the following rule, all three block grids overflow their parent and subsequently overflow the view port. i don't immediately see any errors in my html. any ideas?

```css
@media only screen {

.footer ul {
     max-width:100%;
}

}

```
```html
<div class="row collapse">
	<div class="large-12 medium-12 small-12 columns footer">
		<div class="large-12 medium-12 small-12 columns">
			&nbsp;
		</div>
		<div class="large-6 medium-12 small-12 columns">
			<h4 class="handlee bolder brown">Site Links</h4>
			<hr class="no-pad-top">
			<ul class="small-block-grid-3 medium-block-grid-3 large-block-grid-3 varela footer-links">
				<li><a href="http://crossbows.openex.info/">Home</a></li>
				<li><a href="http://crossbows.openex.info/faq">FAQ</a></li>
				<li><a href="http://crossbows.openex.info/about">About Us</a></li>
				<li><a href="http://crossbows.openex.info/terms">Terms</a></li>
				<li><a href="http://crossbows.openex.info/privacy-policy">Privacy Policy</a></li>
				<li><a href="http://crossbows.openex.info/contact">Contact Us</a></li>
			</ul>	
		</div>	
		<div class="large-3 medium-6 small-12 columns">
			<h4 class="handlee bolder brown">Social</h4>
			<hr class="no-pad-top">
			<ul class="small-block-grid-3 medium-block-grid-3 large-block-grid-3 social">
				<li><a href="#" class="fi-social-facebook"></a></li>
				<li><a href="#" class="fi-social-twitter"></a></li>
				<li><a href="#" class="fi-social-google-plus"></a></li>
				<li><a href="#" class="fi-social-instagram"></a></li>
				<li><a href="#" class="fi-social-github"></a></li>
				<li><a href="#" class="fi-social-skype"></a></li>
			</ul>
		</div>
		<div class="large-3 medium-6 small-12 columns">
			<h4 class="handlee bolder brown">Unused Section</h4>
			<hr class="no-pad-top">
			<ul class="small-block-grid-3 medium-block-grid-3 large-block-grid-3">
				<li><a href="#">Test</a></li>
				<li><a href="#">Test</a></li>
				<li><a href="#">Test</a></li>
				<li><a href="#">Test</a></li>
				<li><a href="#">Test</a></li>
				<li><a href="#">Test</a></li>
			</ul>
		</div>
		<div class="large-12 medium-12 small-12 columns">
			<hr class="no-pad">
			<p>&copy; 2015 AllCrossbows.com</p>
		</div>
	</div>
</div>
```

**Comment by gakimball** [comment]
Thanks for posting all of your markup. A few comments on your HTML:

First, you probably don't need that outer row and column. You have five columns inside of your nested grid, so you could just position those right inside your first row. Second, you don't need to repeat the grid classes if the numbers are the same. The framework is mobile-first, so writing `small-12` means that *every* screen size will see a 12-wide column. That means writing `small-12 medium-12 large-12 columns` is unnecessary; you can just write `small-12 columns`. Same goes for the block grid.

With those two changes your markup would look like this:

```slim
.row
  .small-12.columns &nbsp;
  .large-6.columns
    .small-block-grid-3
  .large-3.medium-6.small-12.columns
    .small-block-grid-3
  .large-3.medium-6.small-12.columns
    .small-block-grid-3
  .small-12.columns
    p &copy; 2015
```

Now as far as the block grid overflowing, because it's inside of a collapsed row, there's no padding on the columns to compensate for the negative margins on the block grid. Your solution of `max-width: 100%` will work, or you can strip the margins off of the block grid.

```css
.row.collapse ul[class*="block-grid"] {
  margin-left: 0;
  margin-right: 0;
}
```

Will a fix land in the framework? It seems a little risky. We could add a rule like the above to the framework, but it's hard to say if it would mess up anyone's existing designs, this late in the life of the framework.

**Comment by r3wt** [comment]
i agree, i just thought i would report it. thanks for clarifying!
