### ISSUE TITLE
Is there a way to apply the grid to table columns?

### ISSUE THREAD

**Issue by marnen** [zurb/foundation#6232]
I have a `<table>` element on my site to display tabular data, and I'd like to use the grid system to give it consistent column width. Is there a way to do this? Applying the `small-# columns` classes to the `<td>` elements doesn't seem to give satisfactory results.

**Comment by eossipov** [comment]
you would apply the table on top of the grid element.

**Comment by marnen** [comment]
How would I do that? I'm not sure I understand what the markup would look like.

**Comment by rafibomb** [comment]
The <a href="http://foundation.zurb.com/forum">Foundation forum</a> would be a great place to seek some help with troubleshooting what might be going on here. If it turns out to be a defect, you'll have some more info to provide here which will help prioritize and get it fixed.

We're trying to keep the issue list focused on confirmed defects in Foundation, so any help everyone can provide to differentiate between usage / troubleshooting and actual defects is appreciated!

**Comment by marnen** [comment]
Sorry, I thought the forum was dead, give that the last several threads are spam. I'll ask there.

**Comment by marnen** [comment]
Posted to forum at http://foundation.zurb.com/forum/posts/22313-grid-system-on-table-columns.

**Comment by rafibomb** [comment]
The forum is the place for answers, in fact you have an answer on your post ;)
