### ISSUE TITLE
Top-bar nav isn't working on small screens

### ISSUE THREAD

**Issue by dyetube** [zurb/foundation#6246]
This project is in an asp.net c# masterpage.  Here's my code:

    <form runat="server">
      <Header class="row" id="masterpageHeader">
       <nav class="top-bar" data-topbar role="navigation">
        <ul class="title-area">
         <li class="name">
         <h1><a href="#">Melissa Community Outreach</a></h1>
         </li>
         
        <li class="toggle-topbar menu-icon"><a href=""><span>Menu</span></a>
        </li>
       </ul>
      <section class="top-bar-section">
      
       <ul class="right">
        <li class="active"><a href="#">Giving</a>
        </li>
        <li class=""><a href="#">Volunteering</a>
        </li>
        <li class=""><a href="#">Hours</a>
        </li>
        <li class=""><a href="#">Location</a>
        </li>
        <li class="has-dropdown">
        <a href="#">About</a>
         <ul class="dropdown">
         <li  class="active"><a href="#">Mission Statement</a>
         </li>
         <li><a href="#">Directors</a>
         </li>
        </ul>
        </li>
        </ul>
        
        <ul class="left">
         <li>
         <a href="#">Privacy Policy</a>
         </li>
        </ul>
       </section>
      </nav>
     </Header>

        <main>
            <asp:ContentPlaceHolder ID="MainContent" runat="server"/>
        </main>
    <footer>
    
    </footer>
    </form>
    <script>
        $(document).foundation();
  </script>

When I click the menu button (or 3 bars) when in small screen, it just reloads the page.  What am I doing wrong?  I also checked that the JQuery is loading and it is and I have both foundation and topbar js's loading (Although don't know how to test if they loaded properly).

Jeff,

**Comment by rafibomb** [comment]
I don't see your scripts in this snippet. The top-bar is working on the docs. 
The <a href="http://foundation.zurb.com/forum">Foundation forum</a> would be a great place to seek some help with troubleshooting what might be going on here. If it turns out to be a defect, you'll have some more info to provide here which will help prioritize and get it fixed.

We're trying to keep the issue list focused on confirmed defects in Foundation, so any help everyone can provide to differentiate between usage / troubleshooting and actual defects is appreciated!
