### ISSUE TITLE
How about using BEM-Syntax and shorter class names??

### ISSUE THREAD

**Issue by luxmedia** [zurb/foundation#6252]
Hello,

How about using BEM-Syntax and shorter values for the css classes??

Instead of using:
```sass
.button {
.primary {}
}
```
you could use:
```sass
.btn {
&--primary {}
}
```

For me BEM is much more consistent and self-explaining than proprietary variable naming. To save some more bits of code i try to use shorter class names for example with striping out the vocals while keeping at least 3 characters and understandable declarations. `medium` becomes `med`, `small` becomes `sml`, `round` becomes `rnd`, `clearfix` becomes `cf` and so on. In combination with BEM-syntax every usual programmer should be able dig into the code with ease and the framework syntax would be more standardized.
Also object-states should be named with an `is-`prefix. This is at least imho a must.

I have build my own foundation fork based on stylus and i am continuously converting it to BEM and shorthands. But everytime i merge the updates from the zurb foundation fork i have to rebuild any overridden changes manually. Of course, its my problem, but a bit of naming-standardization would be very nice and a point for foundation in comparison to its competitor bootstrap.

What do you think?

Best regards
Volker Lux

**Comment by gakimball** [comment]
Our classes are deliberately written as plain English, which is why they aren't namespaced or abbreviated. Especially for components like buttons, which have a lot of classes, we find `small secondary button` to be easier to work with than `btn btn--secondary btn--sml`. For Foundation 6 our stance on this isn't likely to change.

That being said, for the next version of framework we do have a few goals in mind for the HTML/CSS, namely better conforming to HTML semantics, accessibility for all components, more class and less tag selectors, and more consistent naming of CSS classes.
