### ISSUE TITLE
Columns adds bottom margin 10 px and prevents divs from being side by side

### ISSUE THREAD

**Issue by cjfagerstrom** [zurb/foundation#6265]
I was using foundation 5.4.5 in my RoR project and I just updated to 5.5.1. In both cases I had an issue where a row with two small-6 columns would not keep the content level. The content in the right small-6 div would always start at the bottom of the left small-6 div. This happens even if there is no content in the div, which I could verify with Inspect Element on Chrome. When I changed it to column instead of columns, I noticed that the 10px bottom margin that each div had disappeared and the content sat side by side as I intended. The minute I added the s to column for either div, the 10px bottom margin reappeared on that div and the div on the right would scoot down below the end of the column on the left.
![column](https://cloud.githubusercontent.com/assets/8467145/6092313/702bd66e-ae9e-11e4-8c1e-b3cdc7cee063.PNG)
![columns](https://cloud.githubusercontent.com/assets/8467145/6092314/7448d206-ae9e-11e4-8558-ee9f00b9e940.png)

**Comment by gakimball** [comment]
Can you open the inspector and see what line of CSS is creating the styles?

**Comment by rafibomb** [comment]
The <a href="http://foundation.zurb.com/forum">Foundation forum</a> would be a great place to seek some help with troubleshooting what might be going on here. If it turns out to be a defect, you'll have some more info to provide here which will help prioritize and get it fixed.

We're trying to keep the issue list focused on confirmed defects in Foundation, so any help everyone can provide to differentiate between usage / troubleshooting and actual defects is appreciated!
