### ISSUE TITLE
Foundation is not compatible with Cloud Zoom

### ISSUE THREAD

**Issue by galyanoff** [zurb/foundation#6271]
Hi.
Cloud Zoom does not work with the Foundation
https://github.com/sos4nt/cloud-zoom/wiki/Cloud-Zoom

You can consult a similar plug-in that works with the Foundation?
Thanks.

**Comment by Lynda333** [comment]
While I haven't used that plugin before, what doesn't work?

In some cases one must override Foundations max-width. Foundation has this in their code: 

img {
  max-width: 100%;
  height: auto; }

Which I then override in my CSS using this:

    .container-for-plugin img{
		max-width:none;
    }

Hope this helps!

**Comment by galyanoff** [comment]
Thanks for the answer! 
Unfortunately does not work. 
Here is an example of two pages. 

Without using the Foundation, there is a plugin works:
http://soberisy.ru/nofoundation/

At Foundation. The plugin does not work:
http://soberisy.ru/foundation/

Possible conflict with the version of Jquery?

**Comment by irwing-reza** [comment]
This seems to be a jQuery version issue.
"jQuery 2.x has the same API as jQuery 1.x, but does not support Internet Explorer 6, 7, or 8."

**Comment by rafibomb** [comment]
The <a href="http://foundation.zurb.com/forum">Foundation forum</a> would be a great place to seek some help with troubleshooting what might be going on here. If it turns out to be a defect, you'll have some more info to provide here which will help prioritize and get it fixed.

We're trying to keep the issue list focused on confirmed defects in Foundation, so any help everyone can provide to differentiate between usage / troubleshooting and actual defects is appreciated!
