### ISSUE TITLE
Dropdown direction option not working on dynamically added elements

### ISSUE THREAD

**Issue by nicomak** [zurb/foundation#6277]
When loading html by ajax, elements which have the "data-dropdown" attribute have their dropdown working quite well, except that the dropdown direction data-options="align:left" is not taken into consideration. 
I have to call $(document).foundation() in order for the direction to start working again.

**Comment by jeaniec** [comment]
This is expected behavior. Any time you insert dynamically generated content on the page, foundation should be reinitialized OR you can call on the individual component's reflow method. But since the dropdown component currently doesn't have a reflow method (next release!), initializing $(document).foundation() is the way to do it.

http://foundation.zurb.com/docs/javascript.html
