### ISSUE TITLE
PrePros 5.2 and Foundation, @import "foundation/functions"; is unreadable?

### ISSUE THREAD

**Issue by FlannelBeard** [zurb/foundation#6280]
Using Prepros 5.2 and the latest Foundation. 

I don't use grunt, libsass, rails, nothing. I'm a front-end web guy. Nothing fancy, I just build WordPress theme sites. I use prepros to compile my sass, using a config.rb to state where my bower_components folder is and output the sass to my stylesheets folder in my theme. This works on older versions of prepros, not prepros 5+ ... 

I'm getting this error when compiling: 

    Error: File to import not found or unreadable: foundation/functions.
       Load paths:
         F:/Elevancement/@localhost/elixir/wp-content/themes/Elixir/scss
         c:/Program Files (x86)/Prepros/resources/app/ruby/ruby_gems/gems/bourbon-4.0.2/app/assets/stylesheets
         c:/Program Files (x86)/Prepros/resources/app/ruby/ruby_gems/gems/neat-1.7.0/app/assets/stylesheets
         c:/Program Files (x86)/Prepros/resources/app/ruby/ruby_gems/gems/bitters-0.10.1/app/assets/stylesheets
         F:/Elevancement/@localhost/elixir/wp-content/themes/Elixir/scss/sass
         c:/Program Files (x86)/Prepros/resources/app/ruby/ruby_gems/gems/compass-core-1.0.1/stylesheets
         Compass::SpriteImporter
        on line 58 of _settings.scss
        from line 1 of app.scss
      Use --trace for backtrace.

The problem seems to lie (I think?) with `@import "foundation/functions"; `

My config.rb: `add_import_path "bower_components/foundation/scss"`

Does anyone have any idea how to get this working? This seems silly.

**Comment by rafibomb** [comment]
Not sure if this is a Foundation issue...

The <a href="http://foundation.zurb.com/forum">Foundation forum</a> would be a great place to seek some help with troubleshooting what might be going on here. If it turns out to be a defect, you'll have some more info to provide here which will help prioritize and get it fixed.

We're trying to keep the issue list focused on confirmed defects in Foundation, so any help everyone can provide to differentiate between usage / troubleshooting and actual defects is appreciated!

**Comment by jacobmasters** [comment]
Same issue here, think its something with the version of sass and rem calcs...

**Comment by arvi** [comment]
I'm having the same issue...

**Comment by ariane1001** [comment]
anyone found the solution? I have the same issue and can't find how to fix it.

**Comment by jonatasfreitasv** [comment]
Import only foundation.scss !! function is not necessary.
