### ISSUE TITLE
Add support for xlarge and xxlarge

### ISSUE THREAD

**Issue by AlexLaforge** [zurb/foundation#6292]
@ Dev team : Please just remember to put xlarge-12 and xxlarge-12 classes into the complete foundation.css file !
That's a shame I would have to use SCSS to get it : I'm just using pure CSS. Thank you for everyone !

**Comment by gakimball** [comment]
It's because they're so rarely-used that we only allow you to turn them on in the SCSS version. Those responsive grid classes add a *lot* of extra CSS, so if we add two more breakpoints to the plain CSS download, everyone's going to get that extra filesize, even though the majority of developers don't use `xlarge`, much less `xxlarge`.

We could add it to the customizer for version 6 of the framework. We're making breakpoint names and sizes a lot easier to change in v6.0, so perhaps we could expose that functionality to the customizer as well.

**Comment by AlexLaforge** [comment]
Hi gakimball,
I totally understand the fact that these xlarge grids are not used by a lot of people.
So yes, It really would makes sense to slightly improve the customizer and simply allow us to "include XL grids" in the version 6.
For info : Yet, I have tried to setup my dev environment for ruby, compass and a compiler : that's such an impossible mission on a Mac (especially if that's not the very last generation, because the Apple' shipped ruby version is soooo old, and so closely related to the OS and other programs).
So a more detailed online customizer for Foundation 6 would definitilely make sense ! :-)
