### ISSUE TITLE
drop down bottom alignment problem

### ISSUE THREAD

**Issue by ianxdev3** [zurb/foundation#6315]
I have an image link height 75px, which triggers the drop down panel. Ive noticed in developer tools that this automatically sets the content-drop element top style to 45px in javascript, meaning that the panel overlaps my image link. any ideas how to change this?

Any help much appreciated, thanks

**Comment by rafibomb** [comment]
The <a href="http://foundation.zurb.com/forum">Foundation forum</a> would be a great place to seek some help with troubleshooting what might be going on here. If it turns out to be a defect, you'll have some more info to provide here which will help prioritize and get it fixed.

We're trying to keep the issue list focused on confirmed defects in Foundation, so any help everyone can provide to differentiate between usage / troubleshooting and actual defects is appreciated!
