### ISSUE TITLE
Improved usability/implementation of the switch

### ISSUE THREAD

**Issue by yakou32** [zurb/foundation#6316]
I think the switch code is not so nice.
The label can not be used to add a label text ; and a switch interaction should be easily bound to a readable label...

A possible workaround would be to manually add a text next to the switch interaction item. However, clicking on this fake label will not trigger the switch without Javascript...

It therefore becomes quite tricky to use this Switch item...

**Comment by rafibomb** [comment]
We'll be re-writing it for the next version.

We added this to our "known issues" section in our planning board for the next version. A PR would be valuable to the community, otherwise It will be addressed then. You can see and vote on the proposed updates here: https://trello.com/b/QBPKlQqf/foundation-sites

**Comment by rafibomb** [comment]
Here's one way it is done: http://codepen.io/ThatRedHead/pen/qhkGg
