### ISSUE TITLE
Reveal modal event bindings are calling twice

### ISSUE THREAD

**Issue by khawerrind** [zurb/foundation#6334]
The reveal modal event bindings like `open`, `opened`, `close`, `closed` are being called twice. I have created a fiddle to demonstrate the issue. When you will open the modal you will see that the alert is being called twice. 

close: http://jsfiddle.net/u8dfcw0h/
closed: http://jsfiddle.net/u8dfcw0h/1/
open: http://jsfiddle.net/u8dfcw0h/2/
opened: http://jsfiddle.net/u8dfcw0h/3/

**Comment by alindber** [comment]
Noticed v5.5.1 doesn't have this issue:  https://jsfiddle.net/alindber/16hsq03o/3/

**Comment by Lynesth** [comment]
I confirm the bug isn't present in 5.5.1.

**Comment by Holek** [comment]
Wrong, this bug **[is present](https://github.com/zurb/foundation/blob/v5.5.1/js/foundation/foundation.reveal.js#L308)** in 5.5.1. It is, however, [gone in current master](https://github.com/zurb/foundation/blob/master/js/foundation/foundation.reveal.js#L336)

**Comment by Lynesth** [comment]
Hey there.

@Holek : You are indeed right. But the bug was already fixed for the "open" trigger, and I didn't check further, my bad.

Anyway, I just realized I didn't take much time looking into namespaced events before and didn't know that jQuery would fire ```event.*``` when someone simply triggers ```event```.
I guess this works just like css selectors.

This may sound stupid and all, I don't know really, but shouldn't we change events to match this pattern ```fndtn.plugin.event``` ? Or do we want that a ```trigger('click')``` also fires ```click.fndtn.plugin``` on the element ?

I don't know really, just having a thought here.

Regards,

Lyn.

**Comment by jeanieshark** [comment]
@Lynesth We're currently undergoing an audit of our current JS codebase to figure out the best ways to handle events so that they're easily extendable but also already come with a set of trigger handlers with expected behaviors of a component. For now, just use the event triggers as you were before, and we'll update our documentation in F6 for the proper way of using and extending event triggers.
