### ISSUE TITLE
Reveal `open` event doesn't fire on dynamically created modals.

### ISSUE THREAD

**Issue by kylefox** [zurb/foundation#6341]
The `"open.fndtn.reveal"` event does not fire on modals which have been manually created using JavaScript and then opened with `modal.foundation('reveal', 'open');`

### Steps to reproduce

1. Attach a document event handler to `"open.fndtn.reveal"`
1. Construct the markup for a Reveal modal element, `$elm`, using JavaScript.
1. Manually open the model using `elm.foundation('reveal', 'open')`

### Expected Behavior

The document `"open.fndtn.reveal"` event handler fires.

### Actual Behavior

The document event handler **does not fire.**

### Example

https://jsfiddle.net/u8dfcw0h/4/

_(Note: in the example you'll see the events fire twice — this is due to #6334)_

**Comment by DavisDevelopment** [comment]
### Solution

First, you need to create a **function** which binds your relevent event-listeners to the document.
Invoke it once, right off the bat (directly under it's declaration).

Then, when you create the Element for your Modal, you need to:
 1. Append your Element to the body of the document
 2. Re-Invoke Foundation (`$(document).foundation()`)
 3. Re-Invoke your event-binding function
 4. **THEN**, you can open your Modal, and all the expected events will be fired

#### Fixed Example
https://jsfiddle.net/kronocian/u8dfcw0h/8/

I don't know if you *need* the event-handler to be bound to `document`, instead of your modal itself, but the latter would be advisable, so that you're not having to re-bind your events every time you create a new modal.

**Comment by Lynesth** [comment]
Hey there.

@kylefox : The only thing you are missing is to actually append the newly created modal to the body.
Just adding the following line fixes everything :

```javascript
        $modal.appendTo("body");
```

You can see it here : https://jsfiddle.net/u8dfcw0h/9/

I'm not sure this should be considered as a real issue, and even if it is, it's really not important to try to fix IMHO.

Kind regards,

Lyn.

**Comment by rafibomb** [comment]
Thanks @Lynesth and @DavisDevelopment
