### ISSUE TITLE
Cannot add custom class to tooltips

### ISSUE THREAD

**Issue by simonwimell** [zurb/foundation#6349]
The documentation states that I should be able to add a custom class to tooltips using data-options, but it just doesn't seem to work. I've tried this:

    data-options="tooltip_class: '.newstip';"
    data-options="tooltip_class: 'newstip';" 
    data-options="tooltip_class: .newstip;"
    data-options="tooltip_class: newstip;"

There is a closed (I can't see why) issue about this: #3542

**Comment by Lynesth** [comment]
Hey there !

I agree that this is not working and I wonder why the other issue ended up with such answers.
After giving it a look, I think this should be fixable with just those 2 modifications :

On line 17 of foundation.tooltip.js :
```javascript
tip_template : function (selector, tooltip_class, content) {
        return '<span data-selector="' + selector + '" id="' + selector + '" class="tooltip '
          + tooltip_class + '" role="tooltip">' + content + '<span class="nub"></span></span>';
      }
```

and line 167 of the same file :
```javascript
      var $tip = $(tip_template(this.selector($target), settings.tooltip_class.substring(1), $('<div></div>').html($target.attr('title')).html())),
```

Here is a messy jsfiddle showing it in action : http://jsfiddle.net/qq6nzxaj/

This deliberatly keep the "tooltip" class on the tooltips, because I like just adding some little modifications without rewriting it all and removing it may mess it all up anyway because of how this plugin is currently coded (no offense to anyone here).

Regards,

Lyn.

**Comment by rafibomb** [comment]
We added this to our "known issues" section in our planning board for the next version. A PR would be valuable to the community, otherwise It will be addressed then. You can see and vote on the proposed updates here: https://trello.com/b/QBPKlQqf/foundation-sites
