### ISSUE TITLE
`.hide` class no longer works on `.error` elements

### ISSUE THREAD

**Issue by kruszczynski** [zurb/foundation#6358]
I've just updated from Foundation 5.4.7 to 5.5.1 and I had lots of `small.error` elements in my forms that I always had rendered but added and remove `.hide` class via JS when necessary (it's a Single Page App).

I was looking for a fix at first, but I'm not this familiar with foundation code base to go straight to a Pull Request. With some pointers from you guy's I'll be happy to be the one fixing that.

In `_forms.scss:306` there's the reason:
```sass
@mixin form-error-message($bg:$input-error-message-bg-color) {
  display: block;
  ...
}
```
That's included in `small.error` in `_forms.scss:534`
```sass
span.error, small.error {
  @include form-error-message;
}
``` 
Therefore `display: block` in `small.error` takes precedence over `display: none` of `.hide`

For now I can monkey-path this with such code in my project-specific stylesheet:
```sass
small.error.hide {
  display: none;
}
```
But definitely it's not the final fix for this problem. Maybe a mixin like this would be a solution:
```sass
@mixin display-block {
  display: block;
  &.hide {
    display: none;
  }
}
```

**Comment by kruszczynski** [comment]
FYI I've ran into similar issue with `.button`s as well.

**Comment by laantorchaweb** [comment]
this seems to be related to taking away the !important on the hide class #6190

**Comment by kruszczynski** [comment]
Do you guys have a fix planned? I was thinking about 
```
@mixin display($display: block) {
  display: $display;
  &.hide {
    display: none;
  }
}

.button {
  @include display(block);
}
```

I'd be happy to create a PR with this solution. Will do so in the next few days.

**Comment by AlecRaeside** [comment]
Yeah the change to `.hide` was quite major (just found out after debugging a separate issue), its odd that the change was included in a patch release.

**Comment by gakimball** [comment]
So I'm assuming you started a new project on Foundation 5.4.7, because that's when the change to the `.hide` class made it in. However, changing that class was a mistake, which is why we removed the `!important` recently. *That* change made it in with 5.5.1. So not having `!important` was the intended behavior. (See #6190 for that discussion.)

Since you've been writing your code with that version of `.hide` in mind, it shouldn't harm your design if  you override it yourself.

```scss
.hide {
  display: none !important;
}
```

We just had to change it back for existing users, who were used to the class working another way.

**Comment by kruszczynski** [comment]
@gakimball I started my project on Foundation 5.5.1

I know that not having the `!important` on `.hide` was intended and I think it is a good idea. 

I also think that with html like that:
```html
<small class="error">Something went wrong</small>
```
it reasonable for me to expect that adding hide class to such element would hide it. However it is not the case i current code base because `small.error` (`_forms.scss:540`) selector is stronger then `.hide` selector. That's what I think should be improved because the hide class does not work as expected.

It is possible however that I don't really understand your intentions and what everyone should do from now on is what I've done in my project: 
```scss
small.error.hide { display: none; }
```
And I'm fine with that but in such case I think [this section of the docs](http://foundation.zurb.com/docs/utility-classes.html) should reflect that more or be removed.

**Comment by gakimball** [comment]
We can add a note to the docs that `.hide` is the only class that doesn't have `!important` on it.

As for your specific issue, it usually doesn't come up because any form error inside a `[data-abide]` element gets `display: none`, which is how we hide them.

It would be nice if we could just reduce the specificity of the error styles by removing the tag, but form labels and form errors both share the `.error` class, so we can't. We've already addressed this in Foundation 6 thankfully, by using different classes for labels, fields, and error text.
