### ISSUE TITLE
Abide and success message

### ISSUE THREAD

**Issue by cortopy** [zurb/foundation#6362]
I was trying to implement a success message to create live validation with Abide. However, I'm not able to show it. 

In the form I'm using

```
<small class="success" style="display:none">Got it!</small>
```

And then in my js

```
$('#co-billing-form')
  .on('valid.fndtn.abide', function () {
    $ ( '.success' ).show();
  });
```

But it's not working. Is it because the valid event only happens with form submission? Which event does trigger the error message to show? Can it be replicated for success messages too?

**Comment by rafibomb** [comment]
The <a href="http://foundation.zurb.com/forum">Foundation forum</a> would be a great place to seek some help with troubleshooting what might be going on here. If it turns out to be a defect, you'll have some more info to provide here which will help prioritize and get it fixed.

We're trying to keep the issue list focused on confirmed defects in Foundation, so any help everyone can provide to differentiate between usage / troubleshooting and actual defects is appreciated!

**Comment by ali-sao** [comment]
Actually there are no answers @foundation forum . and am seeking the same answer
