### ISSUE TITLE
Range Slider problem

### ISSUE THREAD

**Issue by brunocascio** [zurb/foundation#6379]
```
<label>Cant. demandadas
 <div class="range-slider round" data-slider data-options="step:1; start: 1; end: {{p.max}};">
   <span class="range-slider-handle" role="slider" tabindex="0"></span>
   <span class="range-slider-active-segment"></span>
   <input type="hidden" ng-model="p.cantDemand" />
 </div>
</label>
```

```
<script src="js/vendor/jquery.js"></script>
<script src="js/foundation/foundation.js"></script>
<script src="js/foundation/foundation.slider.js"></script>
<script src="js/angular.js"></script>
<script>
$(document).foundation();
</script>
```

Console output when slide range.

`Uncaught TypeError: Cannot read property 'vertical' of undefined`

**Comment by Lynesth** [comment]
Hey there,

I am not able to reproduce this behavior (https://jsfiddle.net/hmoehts8/ working).
Could you link to a page where we could witness it ?

Regards,

Lyn.

**Comment by rafibomb** [comment]
The <a href="http://foundation.zurb.com/forum">Foundation forum</a> would be a great place to seek some help with troubleshooting what might be going on here. If it turns out to be a defect, you'll have some more info to provide here which will help prioritize and get it fixed.

We're trying to keep the issue list focused on confirmed defects in Foundation, so any help everyone can provide to differentiate between usage / troubleshooting and actual defects is appreciated!

**Comment by brunocascio** [comment]
The problem is related with angular/foundation, but without angular, range slider works fine...

**Comment by irothenbaum** [comment]
The problem is not just related to angular. I believe it's an actual bug with Foundation. Here is a simple JSFiddle the demonstrates the problem.
https://jsfiddle.net/w81p4ux2/

Please consider issuing a fix.
