### ISSUE TITLE
!global is redundant

### ISSUE THREAD

**Issue by quinn** [zurb/foundation#6392]
the use of !global here does nothing: https://github.com/zurb/foundation/blob/master/scss/foundation/_functions.scss

and can be removed. `$modules` is already defined on the global scope and therefore modifications to it within the `supports` mixin are global.

**Comment by gakimball** [comment]
Are you referring to line 14 or line 18, or both?

**Comment by quinn** [comment]
both, mine seems to work fine without it there at all.

**Comment by gakimball** [comment]
Check your CSS, you probably have duplicate output. (Try searching for `html ,body` specifically, since that will definitely output more than once.)

I believe line 14 is unnecessary because *accessing* the global scope is automatic, but *modifying* it is not. Load [this gist](http://sassmeister.com/gist/b97b912706081889bd2f) to see an example. If you remove `!global` from line 7, the change to `$var` won't be applied globally.

**Comment by quinn** [comment]
thanks @gakimball for the clarification about how global scope works. This must be a bug in my implementation then (I am not using the canonical implementation). Sorry for the trouble.

**Comment by gakimball** [comment]
Ah yeah, I forgot to mention that libsass doesn't have the changes to variable scope yet; this is only for Ruby Sass. Thankfully our `exports()` mixin pretty much works the same either way.
