### ISSUE TITLE
Top-bar dropdown parent link duplicated on medium breakpoint

### ISSUE THREAD

**Issue by rafibomb** [zurb/foundation#6393]
Confirmed in Chrome and Firefox http://codepen.io/rafibomb/pen/KwGYge

When in the medium breakpoint, the parent link of the dropdown is duplicated in the dropdown.
http://foundation.zurb.com/forum/posts/23372

**Comment by prbfun** [comment]
Hi All, I am newly learning to make sites using Foundation and faced the same problem....

In Version 5.5.1 full download,
I changed line number: 4759 in file > foundation.min.js located in the js folder
changed:
mobile_show_parent_link : true,
to:
mobile_show_parent_link : false,

and the problem was gone... no more duplicate link showed anywhere (including mobile)

Thanks,
Prasadh

**Comment by yogiderek** [comment]
Hi

In v5.5.1 foundation.topbar.js Line 375, change the following from

class="parent-link hide-for-large-up" 
to
class="parent-link hide-for-medium-up"       or class="parent-link show-for-small-only"

This cleared my problem

Derek

**Comment by Tralapo** [comment]
@prbfun I changed the line you point out in foundation.topbar.js on line 14. Works fine!

**Comment by rafibomb** [comment]
Fixed, thanks!
