### ISSUE TITLE
Open reveal on click with JavaScript

### ISSUE THREAD

**Issue by LeG3nDz** [zurb/foundation#6396]
Hi community,

I would like open my image on modal without add my <img> on #myModal. So i test with this, but when #myModal appears, the .reveal-modal-bg is hidden :(

.reveal-modal-bg is hidden only if I change the html of #myModal.

My HTML :

    <a class="image-modal" data-img-src="/path/to/image.jpg" data-reveal-id="myModal">
        Click Me
    </a>

And JavaScript :

    $('a.image-modal').on('click', function() {
        var img = $(this).data('img-src');
        var revealId = $(this).data('reveal-id');
        $('#' + revealId).html('<img src="' + img + '" alt=""/>').foundation('reveal','open');
    });

Any idea ?

Thank youuuu :)

**Comment by rafibomb** [comment]
The <a href="http://foundation.zurb.com/forum">Foundation forum</a> would be a great place to seek some help with troubleshooting what might be going on here. If it turns out to be a defect, you'll have some more info to provide here which will help prioritize and get it fixed.

We're trying to keep the issue list focused on confirmed defects in Foundation, so any help everyone can provide to differentiate between usage / troubleshooting and actual defects is appreciated!
