### ISSUE TITLE
Nested AJAX modals do not work

### ISSUE THREAD

**Issue by kerryj89** [zurb/foundation#6400]
Reveal does not apply proper classes for multiple open stacking when opening an AJAX modal within another AJAX modal, however, opening a non-AJAX modal within an AJAX modal behaves correctly and applies the "open" and "toback" classes where needed.

**Comment by rafibomb** [comment]
The <a href="http://foundation.zurb.com/forum">Foundation forum</a> would be a great place to seek some help with troubleshooting what might be going on here. If it turns out to be a defect, you'll have some more info to provide here which will help prioritize and get it fixed.

We're trying to keep the issue list focused on confirmed defects in Foundation, so any help everyone can provide to differentiate between usage / troubleshooting and actual defects is appreciated!
