### ISSUE TITLE
Foundation 5.5.1 Abide | ShadowDOM elements Webshims

### ISSUE THREAD

**Issue by Smolky** [zurb/foundation#6414]
Hi. I have problems with Abide validation using Webshims. The problem happends trying to validate a input type date due to the shadow DOM.

It worked me perfectly on the BLUR event but not triggering the SUBMIT

I think I fixed the prolbem modifying foundation.abide javascript

      form
        .off('.abide')
        .on('submit.fndtn.abide validate.fndtn.abide', function (e) {
          var is_ajax = /ajax/i.test(self.S(this).attr(self.attr_name()));

          // Here! Note the NOT selector
          return self.validate(self.S(this).find('input, textarea, select').not ('.a11yhide-inputbtns').get(), e, is_ajax);

        })
        .on('reset', function () {
          return self.reset($(this));
        })
        .find('input, textarea, select')
          .off('.abide')
          .on('blur.fndtn.abide change.fndtn.abide', function (e) {
            if (settings.validate_on_blur === true) {
              self.validate([this], e);
            }
          })
          .on('keydown.fndtn.abide', function (e) {
            if (settings.live_validate === true && e.which != 9) {
              clearTimeout(self.timer);
              self.timer = setTimeout(function () {
                self.validate([this], e);
              }.bind(this), settings.timeout);
            }
          });

Is a better way to fixed this without modifiy the foundation code?

Thanks!

**Comment by rafibomb** [comment]
The <a href="http://foundation.zurb.com/forum">Foundation forum</a> would be a great place to seek some help with troubleshooting what might be going on here. If it turns out to be a defect, you'll have some more info to provide here which will help prioritize and get it fixed.

We're trying to keep the issue list focused on confirmed defects in Foundation, so any help everyone can provide to differentiate between usage / troubleshooting and actual defects is appreciated!
