### ISSUE TITLE
Tabs: uncaught range error. maximum callstack size exceeded

### ISSUE THREAD

**Issue by r3wt** [zurb/foundation#6425]
Everytime i click a tab in this mobile page, this error pops up twice

![img](http://puu.sh/gRPXs/0aa4a09ae7.png)

**Comment by rafibomb** [comment]
Can't replicate this on the docs.

The <a href="http://foundation.zurb.com/forum">Foundation forum</a> would be a great place to seek some help with troubleshooting what might be going on here. If it turns out to be a defect, you'll have some more info to provide here which will help prioritize and get it fixed.

We're trying to keep the issue list focused on confirmed defects in Foundation, so any help everyone can provide to differentiate between usage / troubleshooting and actual defects is appreciated!
