### ISSUE TITLE
Foundation Variables and Mixins Not Working Correctly

### ISSUE THREAD

**Issue by realph** [zurb/foundation#6426]
I have Foundation installed with Bower, and I'm including the path in my gulp task like so:

    .pipe(sass({
        includePaths: [
            'bower_components/foundation/scss'
        ],
        outputStyle: 'expanded'
    })

When I `@import 'foundation';` into my stylesheet it seems to work fine. But when I start to reference its SASS variables I start getting errors like the one below:

    Error: unbound variable $medium-up

Any idea why this is happening?

Thanks in advance!

**Comment by KatzArie** [comment]
I'm not families with sass enough, but a little google'ing showed me [this](https://github.com/dlmanning/gulp-sass/issues/16), more specificly the dependeancy tree in [#33057635](https://github.com/dlmanning/gulp-sass/issues/16#issuecomment-33057635), maybe it can help.

foundation.scss is not calling any variables, looking at Gruntfile.js, sass worker also calls scss/settings.scss, maybe you're missing `@import settings`?

**Comment by rafibomb** [comment]
The <a href="http://foundation.zurb.com/forum">Foundation forum</a> would be a great place to seek some help with troubleshooting what might be going on here. If it turns out to be a defect, you'll have some more info to provide here which will help prioritize and get it fixed.

We're trying to keep the issue list focused on confirmed defects in Foundation, so any help everyone can provide to differentiate between usage / troubleshooting and actual defects is appreciated!
