### ISSUE TITLE
Minify breaks even button-group

### ISSUE THREAD

**Issue by Tralapo** [zurb/foundation#6440]
I'm experiencing trouble with my even-4 button-group. It turns out the even-part breaks after you minify it, but I wouldn't know why. See the picture below for an illustration. The first one is the original code, the second one is the minified one.

![buttongroup](https://cloud.githubusercontent.com/assets/11296429/6997103/374aae64-dbae-11e4-94b5-34f26f4da96e.jpg)

The example above has the following code, which is working fine as you can see in the above image:

```html
<div class="panel social">
	<ul class="button-group even-4">
		<li><a href="URL" class="button twitter" target="_blank"><i class="fa fa-twitter fa-lg"></i></a></li>
		<li><a href="URL" class="button facebook" target="_blank"><i class="fa fa-facebook fa-lg"></i></a></li>
		<li><a href="URL" class="button googleplus" target="_blank"><i class="fa fa-google-plus fa-lg"></i></a></li>
		<li><a href="URL" class="button whatsapp" target="_blank"><i class="fa fa-envelope-o fa-lg"></i></a></li>
	</ul>
</div>
```

As soon as it get's minified, it breaks the 'even' part. In my case it's automatically minfied, but I found out it doesn't matter if it's minified automatically or just by hand. If I put the code on one line like in the example below, it breaks in the same way. 

```html 
<div class="panel social"><ul class="button-group even-4"><li><a href="URL" class="button twitter" target="_blank"><i class="fa fa-twitter fa-lg"></i></a></li><li><a href="URL" class="button facebook" target="_blank"><i class="fa fa-facebook fa-lg"></i></a></li><li><a href="URL" class="button googleplus" target="_blank"><i class="fa fa-google-plus fa-lg"></i></a></li><li><a href="URL" class="button whatsapp" target="_blank"><i class="fa fa-envelope-o fa-lg"></i></a></li></ul></div>
```

In my eyes, it's strange that this happens. Why wouldn't it be possible to put this code on just one line? Works for every other kind of list.

**Comment by gakimball** [comment]
This is happening because the items within a button group use the property `display: inline-block`. So it looks slightly different if the list items *do* or *don't* have a whitespace character between them. (HTML counts a line break as a whitespace character.) [Here's an explanation](https://css-tricks.com/fighting-the-space-between-inline-block-elements/) of why inline-block elements generate extra whitespace.

The *ideal* way to fix this is to use floats instead of inline-block. It wouldn't be hard to implement, I'm just not sure if it constitutes a breaking change or not. Visually it would look identical, but structurally it would be slightly different.

We've already fixed this in Foundation 6, and since 5 has been out for quite a while right now, we might want to leave this as-is. As for a fix, if you know that your HTML will always be compressed, you can add back in the spacing by hand:

```css
.button-group li:not(:last-child) {
  margin-right: 1px;
}
```

**Comment by Tralapo** [comment]
@gakimball Good point, thanks for explaining. I should have thought about this solution myself haha. It works quite good. I will wait for F6 for the definitive solution.
