### ISSUE TITLE
Foundation Apps - Menu Bars are not responsive.

### ISSUE THREAD

**Issue by JTallis** [zurb/foundation#6455]
The Menu Bars on Foundation Apps is not responsive at all. In a small view, it may end up looking a little like this:

![](http://i.imgur.com/WZzXcx5.png)

This prevents people from getting to various links and is completely undesirable.

Note: Did not realize foundation-apps existed seeing as the github link on http://foundation.zurb.com/apps/support.html pointed to here.

**Comment by gakimball** [comment]
The Apps menu bar has a vertical mode, which you can use to make it responsive. It's not vertical by default on small screens, because you might want a smartphone-style horizontal tab strip.

Because the classes are written mobile-first, your class structure would look like this:

```html
<ul class="vertical medium-horizontal menu-bar">
  <li><a href="#">Item</a></li>
  <li><a href="#">Item</a></li>
  <li><a href="#">Item</a></li>
</ul>
```

Also, sorry about the incorrect link! We'll get that fixed shortly.
