### ISSUE TITLE
redundant dependencies for bower package

### ISSUE THREAD

**Issue by vanilla-thunder** [zurb/foundation#6462]
hello,

i just started replaceing git submodules with bower components in my projects and i have noticed, that foundation bower package does already contain all the vendor scripts but still requires them within the bower.json.
So installing foundation with bower will download the bower package itself, which includes all we need, but also lots of absolutely redundant and useless stuff nobody wants, (especially because the dependency packages contain lots of uncompiled sass/scss/less/coffescript development stuff)

my suggestion is to remove dependencies from bower.json because the package already has everything it needs

**Comment by gakimball** [comment]
This is kinda tricky. You're right that it's redundant, but since we're already doing both, there are likely people that depend on both. Some folks might be hooking into the files we include, while others may be using a tool like [bower-main-files](https://github.com/ck86/main-bower-files) to programmatically include dependencies based on the `bower.json`. Not including the dependencies as actual files is the right way to do it; they should just be declared in `bower.json`.

It might be best to leave this until Foundation 6, which is out in a few months. We'll be reviewing our entire deploy process, as well as how we bundle code for the various package managers we support.
