### ISSUE TITLE
data-equalizer's never initialize inside of tab panel unless tab panel is active on page load

### ISSUE THREAD

**Issue by r3wt** [zurb/foundation#6474]
temporary workaround, assuming your tab's have the `.content` class

```js
$('.content').on('toggled', function (event, tab) {
	$(document).foundation('reflow');
}); 
```

**Comment by gakimball** [comment]
That's the expected behavior, because the plugin can't properly initialize itself if its contents are hidden. For Foundation 6 we're looking into having plugins like tabs perform automatic reflows for situations like this.

You can also localize the reflow call to just Equalizer (or any other plugin that supports reflows):

```js
$(document).foundation('equalizer', 'reflow');
```

**Comment by szyam** [comment]
I'm using Version 6.2.4 and this is still happening. Is it still in the works to have this work? Thanks
