### ISSUE TITLE
(5.5.1) Distributed Accordions not collapsing accordions in the same group

### ISSUE THREAD

**Issue by KeyboardsAreCool** [zurb/foundation#6478]
I used the HTML directly from the documentation page, and ensured I was using the latest version from the CDN. Here is the fiddle:

http://jsfiddle.net/vn4zjLkL/

**Comment by caycek** [comment]
So I really wanted to try and help out and I'm completely new to doing Git help stuff... But if you change line 27 in foundation.accordion.js to S('[' + self.attr_name() + ']') instead of S(this).closest('[' + self.attr_name() + ']') it acts like what you want it to.

Again... I'm not sure where I should report this or make mention or if this is even what you guys want. It doesn't seem to disrupt anything that is working on and only targets accordions with the same attr_name. I feel like that is an important aspect..

**Comment by zurbrandon** [comment]
This has been all fixed up in Foundation 5.5.2. I'll close the issue for now :) Thanks!!!
