### ISSUE TITLE
Error in the settings.scss file

### ISSUE THREAD

**Issue by jgacuca567** [zurb/foundation#6480]
I am running Foundation 5 with Grunt and I after compling the scss file, the error is 

Running "compass:dev" (compass) task
    error sass/main.scss (Line 320 of sass/foundation/_settings.scss: Invalid CSS after "...cordion-classes": expected selector or at-rule, was ": $include-html...")

in the settings.scss file, I have uncommented out the $include-html-accordion classes: $include-html-classes;..

I am using Grunt 0.4.5
Grunt Watch 0.5.3
Foundation Version 5.5.1 

What could be the problem be?

**Comment by rafibomb** [comment]
The <a href="http://foundation.zurb.com/forum">Foundation forum</a> would be a great place to seek some help with troubleshooting what might be going on here. If it turns out to be a defect, you'll have some more info to provide here which will help prioritize and get it fixed.

We're trying to keep the issue list focused on confirmed defects in Foundation, so any help everyone can provide to differentiate between usage / troubleshooting and actual defects is appreciated!
