### ISSUE TITLE
Mistake in the online documentation

### ISSUE THREAD

**Issue by valentincocaud** [zurb/foundation#6483]
After few try and research, I think there is a mistake in the documentation here : [Range Slide - Callbacks](http://foundation.zurb.com/docs/components/range_slider.html#callbacks)

The event for catching value changement is "change" and not the one shown.
If it's not true I d'ont understand why it's works like this in my code.

**Comment by rafibomb** [comment]
We tested it - looks correct `change.fndtn.slider`

The <a href="http://foundation.zurb.com/forum">Foundation forum</a> would be a great place to seek some help with troubleshooting what might be going on here. If it turns out to be a defect, you'll have some more info to provide here which will help prioritize and get it fixed.

We're trying to keep the issue list focused on confirmed defects in Foundation, so any help everyone can provide to differentiate between usage / troubleshooting and actual defects is appreciated!
