### ISSUE TITLE
Tooltip throws error when using AngularJS

### ISSUE THREAD

**Issue by Lukeluha** [zurb/foundation#6503]
I'm using foundation tooltip in modal window - everything is ok. In other div, I have little logic using angular. When I interact with this content - angular observes it - and I can see `Uncaught TypeError: undefined is not a function` in console (in file jquery.js). When I deleted tooltip from modal window, everything is ok.

This is my code in modal window - it is between `<form>` tag
    
    <div id="newActivity" class="reveal-modal" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
        ....
        <p>
		<i data-tooltip aria-haspopup="true" class="fi-info cursor-pointer"
		   title="title"></i>
       </p>
        ....
    </div>

Interesting is, that tooltip is totally somewhere else as Angular div is.

**Comment by Randore** [comment]
if you can share your code with jsfiddle or screenshots that would be easy to answer your question.

**Comment by rafibomb** [comment]
We're not supporting an Angular version of Foundation Sites for now.

The <a href="http://foundation.zurb.com/forum">Foundation forum</a> would be a great place to seek some help with troubleshooting what might be going on here. If it turns out to be a defect, you'll have some more info to provide here which will help prioritize and get it fixed.

We're trying to keep the issue list focused on confirmed defects in Foundation, so any help everyone can provide to differentiate between usage / troubleshooting and actual defects is appreciated!
