### ISSUE TITLE
bower-foundation does not install `/assets` folder

### ISSUE THREAD

**Issue by uglymunky** [zurb/foundation#6509]
When I install foundation using [bower](https://github.com/zurb/bower-foundation) I get `js`, 'css', and `scss`, but no images.

Is this expected behavior?  If so, why?

It seems it would make prototyping quicker if foundation included a set of images that I could reference.

**Comment by gakimball** [comment]
If you need placeholder images for prototyping, we'd recommend using a service like [placehold.it](http://placehold.it). Or for a more fun alternative, [placekitten.com](http://placekitten.com).

The reason we don't include any placeholder images with Foundation is because services like those already do it really well. You just drop a URL with a width and height into an image tag and you're good.

```html
<img src="http://placehold.it/400x300">
```

**Comment by uglymunky** [comment]
Gotcha, thanks.  In many cases using placehold.it has been good enough but sometimes it's good to have an actual icon.  I just came across [font awesome](http://fortawesome.github.io/Font-Awesome/) and I was able to solve my use case by just loading their css.
