### ISSUE TITLE
Topbar dropdown display bug

### ISSUE THREAD

**Issue by krokofant** [zurb/foundation#6536]
Se this JSFiddle for code example: https://jsfiddle.net/nu9fwr5h/

Description:
When clicking on a dropdown item the dropdown disappears as expected but when moving to another browser tab and back - the dropdown is visible again.

Open JSFiddle, Click "My dropdown", Click "Page 1", Switch tab/application and switch back

Temporary solution:
Blurring the a-element which was clicked.

**Comment by rafibomb** [comment]
We see the issue happening although this would likely only affect a SPA because otherwise the user would be directed to another page and if they returned it would re-load the page. 

It's not something we're going to address in this version but SPA use cases are being addressed in the JS of the new version(6) we're working on. Thanks!
