### ISSUE TITLE
Error with Multiple custom validators

### ISSUE THREAD

**Issue by netero** [zurb/foundation#6539]
Documentation says "You can also use multiple custom validators if you wish by separating the names of the custom validators with a space." but this is not working in the last version of Foundation. My code :

<input data-abide-validator="requiredIfVisible rut" id="RUT" maxlength="20" name="RUT" type="text" value="" />

Both custom validators work individually, i hope you can help me.

Regards.

**Comment by rafibomb** [comment]
The <a href="http://foundation.zurb.com/forum">Foundation forum</a> would be a great place to seek some help with troubleshooting what might be going on here. If it turns out to be a defect, you'll have some more info to provide here which will help prioritize and get it fixed.

We're trying to keep the issue list focused on confirmed defects in Foundation, so any help everyone can provide to differentiate between usage / troubleshooting and actual defects is appreciated!
