### ISSUE TITLE
Foundation template doesn't work when dropped into index

### ISSUE THREAD

**Issue by DarrenJansen** [zurb/foundation#6540]
I downloaded Foundation and then directly dropped one of the templates into the index file that came with Foundation. However, Orbit and the Topbar failed to work. 

I'm a newbie; I may have made a mistake, but the Foundation templates page says that you should be able to simply drop the template html directly in the body of the Foundation page.

I finally got it to work by copying it into a Foundation practice file from Lynda.com.

Probably either the instructions on the templates page or the content of the templates or the index file need to be adjusted to make it more intuitive for newcomers to Foundation.

**Comment by rafibomb** [comment]
The <a href="http://foundation.zurb.com/forum">Foundation forum</a> would be a great place to seek some help with troubleshooting what might be going on here. If it turns out to be a defect, you'll have some more info to provide here which will help prioritize and get it fixed.

We're trying to keep the issue list focused on confirmed defects in Foundation, so any help everyone can provide to differentiate between usage / troubleshooting and actual defects is appreciated!
