### ISSUE TITLE
custom validation executing 3 times

### ISSUE THREAD

**Issue by caycek** [zurb/foundation#6547]
A custom validation I wrote is executing 3 times consistently. When the content changes. I'm thinking this is a keyup validation check error, but I haven't found out yet. I'm using the Abide Foundation 5. I'm not sure right now what other information to provide, but if anyone has had this problem or resolved it I would be grateful to hear about it.

**Comment by caycek** [comment]
[6406](https://github.com/zurb/foundation/pull/6406)

Using this did fix the issue, but caused a MAJOR lag in connection for every validation. The current validation is speedy. I just don't need it executing more than once per check.

**Comment by caycek** [comment]
Upgraded to 5.5.2 (only with abide) and it has major lag. I will attempt to diagnose where...

**Comment by rafibomb** [comment]
We added this comment in our planning board for the next version. It would good to make this more performant, however still balancing all the features that people are asking for. 

A PR would be valuable to the community, otherwise It will be addressed then. You can see and vote on the proposed updates here: https://trello.com/b/QBPKlQqf/foundation-sites
