### ISSUE TITLE
Custom build broken: forms always included?

### ISSUE THREAD

**Issue by andig** [zurb/foundation#6550]
I'm trying a custom build from http://foundation.zurb.com/develop/download.html#customizeFoundation including icon-bar, topbar, type and visibility. The result always includes the `_forms.scss` styles which shouldn't be the case.

**Comment by rafibomb** [comment]
The customer uses a SCSS build to compile only the components you choose AND any of the dependancies for that component. In this case, the top-bar partial has the following imports

@import 'global';
@import 'grid';
@import 'buttons';
@import 'forms';

Because you can use a form or a button in top-bar it will import them as well to ensure your styles don't break if you try to use these in top-bar.

If you are using the SCSS version, you can choose the imports in app.scss and you can remove any imported dependancies in the partials. You can also load JS plugins individually.

For the next version we'll make it more explicit that some components depend on others.

**Comment by andig** [comment]
Much appreciated, thank you.

> For the next version we'll make it more explicit that some components depend on others.

Alternatively it might make sense to leave inclusion of buttons and forms up to the user as these are optional contents of the topbar, not required for it to function.
