### ISSUE TITLE
SCSS @import's "forms" and "top bar" are not independent

### ISSUE THREAD

**Issue by ThomasLandauer** [zurb/foundation#6580]
Hi,

Foundation 5, custom component selection in foundation.scss:

To disable form styling (i.e. `<input>`), I have to omit "forms" *and* "top-bar". If either one is active, the form gets styled.

I found another issue which is somewhat related:
https://github.com/zurb/foundation/issues/3811
Maybe the current problem occured when fixing that one - cause they looked at it from the opposite direction ;-)

**Comment by gakimball** [comment]
We might be able to drop some of top bar's dependencies, of which it has three. It imports the grid, buttons, and forms, but oddly only uses variables from one of those: the grid.

In the mean time, if you want to disable the CSS output of the forms module, find the `$include-html-form-classes` variable and set it to `false`.

**Comment by vita10gy** [comment]
One could argue that the overall width that the site is belongs in globals anyway, and that width variable could be used in grid and top-bar.  (either directly or just the default value of variables used in grid and top-bar.)

**Comment by gakimball** [comment]
@vita10gy That's a really good point! Worth considering for sure.

**Comment by gakimball** [comment]
Going to close this, because this change would alter the dependency graph of the components, which is a little risky this late in the game. In Foundation 6 no components have dependencies (except button groups I believe, which depend on buttons), and we also incorporated @vita10gy's idea to have a global width variable that components can share.
