### ISSUE TITLE
Equalizer failing during modal reveal with hover state

### ISSUE THREAD

**Issue by irothenbaum** [zurb/foundation#6630]
It appears that when an equalized div has an active hover state that affects flow (margin, positioning, etc) and is then covered by a modal reveal, the equalized heights revert.

I'm not sure if there's a more simple way to describe this condition, but this fiddle should explain all.
https://jsfiddle.net/4edzcc3p/

To recreate the error in the fiddle, simply click one of the boxes

EDIT: I should also add that the reason I suspect it relates to hover states is that if you place the reveal command inside a timeout and, after clicking the box, remove the cursor from the clicked box before the modal appears, the error does not manifest.

**Comment by tpgmartin** [comment]
This problem seems in part due to this https://github.com/zurb/foundation/blob/master/js/foundation/foundation.equalizer.js#L49

Potential workarounds could be to set the parent div to a fixed height, to `height: inherit` would keep the styles consistent, or to use the `before_height_change` callback http://foundation.zurb.com/docs/components/equalizer.html#callbacks

**Comment by rafibomb** [comment]
Thanks for the report and the example. It's not in our roadmap for equalizer to change it for this use case. If you have a solution though, we'd accept a PR on it to help anyone else that comes across it. We'll close this here. Thanks!
