### ISSUE TITLE
Merge split buttons and button groups together

### ISSUE THREAD

**Issue by ProLoser** [zurb/foundation#6638]
It doesn't make sense to have both of these when the only real difference seems to be that the split button is hard-coded to use a down arrow, which I would like to change. Why not simply allow me to put in whatever icon I want?

**Comment by ProLoser** [comment]
I can't just put plaintext into the split even if I use `.no-pip`

**Comment by gakimball** [comment]
We've already done this for Foundation 6, but the current codebase is maybe a bit too complicated to do that transition right now. We also wouldn't want to deprecate split buttons this late in the game.

But you're saying the `.no-pip` class doesn't work? Could you post a code sample?

**Comment by ProLoser** [comment]
You can't put in _text_, you must use an icon. It looks weird otherwise. If this is not supposed to happen then I will look into if my coworkers royally fucked up the CSS in our app or something (which isn't too out of the question either).

**Comment by gakimball** [comment]
Nope, I was able to recreate this behavior. The dropdown arrow is placed using a pseudo-element with `position: absolute`, so putting text in there just aligns it to the top.

If what you need is a split button where they're both text, I'd recommend using a button group. From a functionality standpoint, they're more or less the same. Actually, the button group works more sensibly because it's two separate buttons. With the split button, the `<span>` inside the `<a>` just prevents click events on it from bubbling up, allowing you to have two links within one anchor.

**Comment by ProLoser** [comment]
I think there are some styling differences such as hovering over the button highlights the entire row, but yes I ended up opting for a button group. I don't actually think having both a split button AND a button group is good design though. Bootstrap doesn't do this, and the use-case the code is covering is sort of odd (and highly specific to event bubbling?)

What I was actually trying to do in the first place was create some sort of number badge on the button similar to the buttons at the top of this page which show fork and star counts. I think fundamentally a better issue that pertains to that is why do we not have badges?

**Comment by gakimball** [comment]
We agree, and like I said we already merged the two components for Foundation 6, but we don't plan on deprecating any existing Foundation 5 components.

We also added a badge for Foundation 6! Foundation for Apps [also currently has a badge](http://foundation.zurb.com/apps/docs/#!/labels-badges) if you want code for one, although they're pretty easy to make.

It kinda sucks that with features like this we have to say "Wait until Foundation 6!", but with version 5 our focus is on keeping it stable, which means not introducing any new features or making big changes this late in the game.

**Comment by ProLoser** [comment]
<img width="213" alt="screen shot 2015-08-05 at 10 44 46 am" src="https://cloud.githubusercontent.com/assets/67395/9093128/07736e54-3b5f-11e5-97e5-661c19b2b375.png">

**Comment by ProLoser** [comment]
Btw after trying to hack the crap out of split button it's been made apparent that we're using `position:absolute` which seems completely unnecessary vs something like inline-block or flex or floats. I think we should drop the use of absolute positioning for something like this.

**Comment by gakimball** [comment]
Agreed, the way it was originally designed was fairly narrow—it's basically just to make those arrows look right.

Since we're about to sunset Foundation 5 from a features perspective, I'm going to close this out. For v6 we've merged split buttons into button groups, and used less precise positioning to make the component more flexible.
