### ISSUE TITLE
Dropdown in nav-bar

### ISSUE THREAD

**Issue by FeroxTL** [zurb/foundation#6645]
Hi,
I'm trying to place dropdown in navbar. Everything seems ok, but when i'm resizing window the dropdown gets out of screen. My code looks like
```
<nav>
<!-- tons of code -->
<li>
    <a data-dropdown="drop2" data-options="align:bottom">login</a>
</li>
</nav>

<div id="drop2" class="f-dropdown content medium" data-dropdown-content="" aria-hidden="true" tabindex="-1">
    <!-- some form content -->
</div>
```

When resizing it looks really bad - 
![142](https://cloud.githubusercontent.com/assets/1344549/8292144/5c0d96d6-1947-11e5-9153-2ce3bfc0a29b.png)

I took debugger and looked for the string
```
//miss right
if (t.offset().left + this.outerWidth() > t.offset().left + actualMarginWidth && t.offset().left - actualMarginWidth > this.outerWidth()) {
```

I really don't understand why first condition is not like this: 
```
 if (this.outerWidth() > actualMarginWidth && t.offset().left - actualMarginWidth > this.outerWidth()) {
```

But it did not made my code work.. I changed it to
```
if (t.offset().left + this.outerWidth() > $(window).innerWidth()) {
```
and it started working at all resolutions. So now the login form always at the right and never out of screen. What have I done wrong? It is some kind of bug?

**Comment by coreysyms** [comment]
I believe you are setting up your top bar a little off. This code worked just fine for me. Give it a whirl.

```
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><a href="#">My Site</a></h1>
    </li>
     <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <li><a href="#">Right Button One</a></li>
      <li>
    	<a data-dropdown="drop2" data-options="align:bottom">login</a>
      </li>
    </ul>

    <!-- Left Nav Section -->
    <ul class="left">
      <li><a href="#">Left Nav Button</a></li>
    </ul>
  </section>
</nav>

<div id="drop2" class="f-dropdown content medium" data-dropdown-content="" aria-hidden="true" tabindex="-1">
    <h3>Login</h3>
    <form>
    	<input type="text">
        <input type="text">
    </form>
</div>
```

**Comment by rafibomb** [comment]
Thanks @coreysyms  I tested your code snippet and it works well. 

@FeroxTL I would check the structure of your markup since you only provided a partial sample. If you still see an issue, please provide a complete example or a codepen would be nice - http://codepen.io/rafibomb/pen/wKzzLo?editors=110

The Foundation forum would be a great place to seek some help with troubleshooting what might be going on here. If it turns out to be a defect, you'll have some more info to provide here which will help prioritize and get it fixed.

We're trying to keep the issue list focused on confirmed defects in Foundation, so any help everyone can provide to differentiate between usage / troubleshooting and actual defects is appreciated!
