### ISSUE TITLE
foundation.css 5.3.1 causes Flash object to reload on print

### ISSUE THREAD

**Issue by cbmtrx** [zurb/foundation#6662]
We detected this error and have been working to find the root cause. When using a Flash SWF (for drawing or painting, for example) and then wanting to print the results, all browsers but Chrome do this with no problem.

On Chrome, however, foundation.css is causing the Flash SWF to reload (thus emptying it)--whether from the File dialog or a print command from within the SWF. When I remove the foundation.css link href, the Flash SWF does not empty.

This is a fairly significant bug as Chrome browser adoption is high.

***UPDATE***

I've narrowed the issue down to line 3516 (at least, of *our* build):
.hide-for-small-only, .hide-for-small-up, .hide-for-small, .hide-for-small-down, .show-for-medium-only, .show-for-medium-up, .show-for-medium, .hide-for-medium-down, .show-for-large-only, .show-for-large-up, .show-for-large, .hide-for-large-down, .show-for-xlarge-only, .show-for-xlarge-up, .show-for-xxlarge-only, .show-for-xxlarge-up {
    display: none !important; }

When I comment out this line, while viewing large, clicking print no longer causes the Flash object to reload. However...this line is ***necessary*** for hiding medium and large views while on a small device!

So how is this to be solved?

**Comment by rafibomb** [comment]
The Foundation forum would be a great place to seek some help with troubleshooting what might be going on here. If it turns out to be a defect, you'll have some more info to provide here which will help prioritize and get it fixed.

We're trying to keep the issue list focused on confirmed defects in Foundation, so any help everyone can provide to differentiate between usage / troubleshooting and actual defects is appreciated!

**Comment by cbmtrx** [comment]
Ok
