### ISSUE TITLE
forms *:disabled

### ISSUE THREAD

**Issue by MoniqueHahnefeld** [zurb/foundation#6676]
Hi,

there is something wrong with this variable in the SCSS-Code: $input-disabled-bg.
The color value defined for $input-disabled-bg also styles the other fields.
The  definition $input-bg-color: #fff; don't work.

Version: 5.2.2

**Comment by jnemeth** [comment]
Hey, can you provide how you are applying the disabled color to the inputs?  Changing the default doesn't seem to be effecting anything that is not disabled.

**Comment by MoniqueHahnefeld** [comment]
Hey I used only the scss-files as original from version 5.2.2 I didn't changed anything at this bundle.

**Comment by rafibomb** [comment]
I can't replicate this issue using this code on the Master branch:

    <input type="text" disabled placeholder="Inputs and other form elements go inside...">

In _settings.scss -  $input-disabled-bg: red;

There has been a change since 5.5.2 that may have fixed the issue you're describing
https://github.com/zurb/foundation/commit/97f7a040b26cb0d9d9e3dbe4b74cbff4567fb41e

Only the disabled input is red.
