### ISSUE TITLE
.button.expand is broken by visibility classes

### ISSUE THREAD

**Issue by ProLoser** [zurb/foundation#6687]
I get setting all buttons to `display: inline` except that should not be the case for `.expand` since on the largest size screen, you want it to be full-width, so why would you want it to be any less on a smaller screen where you pretty much blow up buttons?

**Comment by ProLoser** [comment]
I just realized this is being caused by the visibility classes setting `display: inherit !important;`

**Comment by ProLoser** [comment]
Honestly why do these classes not just define `display: none;` instead of setting the display value to something arbitrary?

**Comment by jnemeth** [comment]
It looks like the issue you mentioned is working fine with hide-for-large-up, please see this quick example: http://codepen.io/jnemeth/pen/eNrWbZ

Can you give us an example of your specific issue?

**Comment by vita10gy** [comment]
@jnemeth I think some links got crossed there. That seems to be unrelated, unless I'm missing something pre comment edits. 

I don't know if the !important is the problem here, but I noted in another issue/pull request that it's likelt possible to ditch the dance of importants here if the specificity is matched on all the elements, like tables parts, which don't work correctly right now anyway.

**Comment by gakimball** [comment]
@vita10gy A revert is not currently possible in CSS, but it's sorely needed. I imagine it would be really hard to implement, though. The [`initial`](https://developer.mozilla.org/en-US/docs/Web/CSS/initial) keyword might help with some of it, but I'm also not fully sure what it does.

I'm not sure why `inherit` was originally used, but using an explicit value `block` would be just as problematic, because it would modify the behavior any non-block element when it comes back into view.

There's not an easy way around this implementation. The main way to get around it is to use containers for visibility, instead of applying the class directly to the element itself.

In Foundation 6 we'll add a set of mixins that recreate visibility classes, but also allow you to define a custom `display` property. It's more flexible and more semantic.

```scss
.element {
  @include show-for(medium, flex);
}
```

In fact, they're simple enough mixins that we could probably just add them to Foundation 5.

**Comment by vita10gy** [comment]
What I meant was, is there a way to do this where we don't need a revert of any form? We don't need to override a display:none with a display:"some" if we never set display:none where we don't mean it in the first place.

**Comment by jnemeth** [comment]
@vita10gy Ack, your correct, I wrote over the previous example in the same pen :(

**Comment by gakimball** [comment]
@vita10gy You could invert the media queries by using `max-width` instead of `min-width`. That would prevent a reset from being necessary. For example, the CSS for `.show-for-large` would be:

```css
@media screen and (max-width: 1023px) {
  .show-for-large {
    display: none !important;
  }
}
```

Now a reset value isn't necessary, because the `display: none` goes away at the large breakpoint. The problem with this is that it's not mobile first, which is *very* important to us at a team. Of course, the class itself is still essentially mobile first, but not the CSS. Mobile-first CSS, among other benefits, gives you an effective non-media-query-browser fallback, so inconsistent use of media queries could prove problematic.

**Comment by vita10gy** [comment]
I see where that might be an issue. I wonder if it wouldn't make sense to make an exception here however, because it can actually potentially cause issues. 

Say you had `<something class='list show-for-medium-only'>`and `.list` had a `display:list-item` in it. Now you have dancing none/inherit/table-header-group/list-item where something is getting trounced. 

Also, !important's are flying everywhere. even though in so many places foundation does a really really good job of not throwing around willy nilly so everything you override has to have them. (unlike what little bootstrap I've worked with and read complaints about) This, I think, can be fixed as-is by specificity matching though. 

I blame css itself for combining two ideas into one property. It really should have been `display:none` and `display:show`, along the lines of visibility except not holding the space,  and then something like `display-as` for `display-as:list-item` `display-as:inline-block` etc. At the very least it doesn't seem like it should have been that hard to see a need for `display:whatever-makes-sense-as-unnone`

**Comment by gakimball** [comment]
@vita10gy Finally got a chance to review this with the team, and we're definitely going to do it for Foundation 6. As for v5, hard to say if we can cleanly implement it without breaking things. (We've made that mistake before!)

Basically, the only reason not to do it is if we care about browsers that don't support media queries. In that case, your wires get crossed slightly, because those browsers will see the mobile styles of every component, *expect* elements that have `.show-for*` classes, which would be in desktop mode.

But we dropped IE8 ages ago, and we're willing to break the mobile-first rule for this one thing. Everything else in the framework should use `min-width` media queries though.

**Comment by vita10gy** [comment]
Sounds like a good plan.

**Comment by gakimball** [comment]
@ProLoser, to your issue, I'd recommend wrapping problematic elements in a visibility class, rather than applying the class directly to the element. It's extra markup, yes, but if that concerns you, it's also fairly easy to recreate a visibility class in Sass:

```scss
.element {
  display: none;

  @media #{$medium-up} {
    display: block;
  }
}
```

**Comment by ProLoser** [comment]
For archival purposes: I ended up wrapping it in another element with the visibility class.

**Comment by hassanbazzi** [comment]
@ProLoser @gakimball Wrapping doesn't solve everything especially if you're trying to use some inline-block features. Consider you have this:

```
<div class="text-center element">
  <img src="whatever.jpg">
  <p>Whatever</p>
</div>

.element {
  > p {
    display: inline-block;
  }
}
```
The goal is to center the two inline-block elements inside the parent container, but you want to hide the paragraph for larger screens. Adding `hide-for-large-up` won't solve it since `display: inherit !important` will kick in. And wrapping the paragraph won't work either since the wrapped div will also be `display: inherit !important` 

I guess you would be able to reverse wrap it where you actually add a `<span class="hide-for-large-up">` inside of the `<p>` tag but that won't necessarily hide the paragraph tag itself and may cause issues.

**Comment by ProLoser** [comment]
```
<p class="text-center element">
  <img src="whatever.jpg">
  <span class="hide-for-large-up">Whatever</span>
</p>
```

**Comment by hassanbazzi** [comment]
That was the first thing I tried too, but `<span>` is an inline element not an inline-block element.
