### ISSUE TITLE
npm version is behind

### ISSUE THREAD

**Issue by peacechen** [zurb/foundation#6698]
Please publish 5.5.1 and 5.5.2 to npm.  As of 7-13-2015, npm shows 5.4.7 as the latest available.

https://www.npmjs.com/package/zurb-foundation-5

**Comment by gakimball** [comment]
Our official package is [foundation-sites](https://www.npmjs.com/package/foundation-sites). The first version we published to it is 5.5.2.

**Comment by peacechen** [comment]
Thanks. Apologies couldn't find that through Google or npm search.
Would it be possible to also publish 5.5.1?  We're having trouble getting the new style event handlers working as documented.  We'll get it fixed up, but it would be really helpful if 5.5.1 were available on npm to tide us over.

**Comment by gakimball** [comment]
Hey, sorry for being *extremely amazingly late* getting back to you on this—our hands have been tied working on Foundation 6 and I let this slip through. If you still need 5.5.1 I can publish it, I just have to do it with a custom tag, because npm prefers you not to publish older versions. No trouble at all, though!

**Comment by andrewcaulfield** [comment]
Hey @gakimball ,

If this could still be published that would be great. There still appears to be an issue in 5.5.3 with magellan #8416 and needs a revert back to 5.5.1.

Cheers
