### ISSUE TITLE
Pagination Unavailable Links Remain Clickable v 5.5.2

### ISSUE THREAD

**Issue by imnes** [zurb/foundation#6709]
Running Chrome on Windows 7.  Using Foundation 5.5.2.

I'm trying to use the pagination as shown in the documentation.  Here's my markup for a first page of results, I want the "Previous" link to be unavailable, and the "Next" link to be available.  

    <ul class="pagination" role="menubar" aria-label="Pagination">
        <li class="arrow unavailable" aria-disabled="true"><a href="">&laquo; Previous</a></li>
        <li class="arrow"><a href="?q=&page=2">Next &raquo;</a></li>
    </ul>

When this renders, the "Previous" link is clickable.

**Comment by jnemeth** [comment]
Instead of:
<code>
    aria-disabled="true"
</code>

Just type:
<code>
disabled
</code>

Unless you are targeting accessibility for screen readers, I'm not sure the <code>aria</code> properties will be useful here.  That said, using both would probably be in order here.

Check out more on aria properties and states here: http://www.w3.org/TR/wai-aria/states_and_properties#aria-disabled

Im going to close this issue.

**Comment by jnemeth** [comment]
Good catch, this appears to be true on my device as well.  I think this could be improved by adding the following to <code>.unavailable</code>:

<code>pointer-events: none;</code>

If you can, please submit a PR for this.

**Comment by zurbrandon** [comment]
This has been added for Foundation 5.5.3. Thanks for bringing it to our attention!
