### ISSUE TITLE
Dropdown alignment broken in Foundation 5.5.2

### ISSUE THREAD

**Issue by johannesluedke** [zurb/foundation#6846]
The dropdown is in the upper left corner instead of below the button that causes the dropdown to open

**Comment by jnemeth** [comment]
Hmm.. Ive got two questions for you:

1.  Which dropdown are you using, regular 'ol dropdown (http://foundation.zurb.com/docs/components/dropdown.html) or dropdown buttons (http://foundation.zurb.com/docs/components/dropdown_buttons.html)?

2.  Have you tried using the alignment data options?

<code>data-options="align:left"</code>

You can now position dropdowns on the top, bottom, left, or right of the target element. 

Hope this helps!

**Comment by rafibomb** [comment]
We'll need to see an example of how to replicate this. Not seeing the issue on the docs.

**Comment by dragthor** [comment]
I am unable to replicate.  Is it a specific browser/OS combo I should be looking at?

**Comment by johannesluedke** [comment]
I experienced the issue with newest Firefox on Ubuntu.

**Comment by rafibomb** [comment]
@johannesluedke We'll need a link to the site or a code sample so we can help you more. We're not able to replicate this on the docs.

The <a href="http://foundation.zurb.com/forum">Foundation forum</a> would be a great place to seek some help with troubleshooting what might be going on here. If it turns out to be a defect, you'll have some more info to provide here which will help prioritize and get it fixed.

We're trying to keep the issue list focused on confirmed defects in Foundation, so any help everyone can provide to differentiate between usage / troubleshooting and actual defects is appreciated!
