### ISSUE TITLE
[DEPENDENCY] jquery.cookie is deprecated

### ISSUE THREAD

**Issue by williamsbdev** [zurb/foundation#6850]
First off, I want to say thank you for this awesome project and providing a bower installable version!

We found that `jquery.cookie` v1.4.1 which is a `bower.json` dependency of the version of foundation we are using (5.5.2). This seems to be the latest version. We are doing a security audit of all our dependencies using the `bower-license` node module and noticed that `jquery.cookie` did not have a license in the `bower.json`. We opened a [PR](https://github.com/carhartl/jquery-cookie/pull/372) on this repo but since it was deprecated, they recommened that we use [js-cookie v2](https://github.com/js-cookie/js-cookie/releases) instead. Since this is a transient dependency we are getting from foundation, foundation would need to update it's dependency.

Is this something the maintainers would consider doing?

Thanks again for this awesome project!

**Comment by SalahAdDin** [comment]
:+1:

**Comment by remy-actual** [comment]
+1 for same reasons re: npm

**Comment by gakimball** [comment]
The cookie library is only used with Joyride, so if you aren't using that plugin, you don't need to include the dependency at all in your production code.

The concern is absolutely valid, but Foundation 5 is now at end of life, so this late in the game we don't really want to swap out a dependency. For v6, Joyride will use localStorage instead of cookies to store data.
