### ISSUE TITLE
Using custom breakpoints with equalizer

### ISSUE THREAD

**Issue by gavinfostered** [zurb/foundation#6852]
Does anyone know if this is possible? Trying to use a custom break point (which was super-easy to create btw!) with equalizer. My custom breakpoint has all the classes generated too using the grid-html-classes mixin. I want to be able to do this with equalizer `<div class="row" data-equalizer data-equalizer-mq="myCustomBreakpoint-up">`

That possible?

**Comment by rafibomb** [comment]
Should work the same way as the default breakpoints. What was your experience?

**Comment by rafibomb** [comment]
The Foundation forum would be a great place to seek some help with troubleshooting what might be going on here. If it turns out to be a defect, you'll have some more info to provide here which will help prioritize and get it fixed.

We're trying to keep the issue list focused on confirmed defects in Foundation, so any help everyone can provide to differentiate between usage / troubleshooting and actual defects is appreciated!

http://foundation.zurb.com/forum
