### ISSUE TITLE
Offcanvas and IE11 bug?

### ISSUE THREAD

**Issue by sebastiansulinski** [zurb/foundation#6870]
I was wondering if anyone else experienced the same problem with Offcanvas in IE11 run in Edge mode - where `right-off-canvas-menu` sticks to the left side and doesn't hide at all? Please see the attached screenshots.

Works fine in Chrome, Safari, Firefox and even IE10, but not 11 (and obviously 9 and lower, but I'm not concerned about the legacy ones).

![01](https://cloud.githubusercontent.com/assets/2211203/9598861/15d94972-5087-11e5-92f6-e457b733b0e5.jpg)
![02](https://cloud.githubusercontent.com/assets/2211203/9598862/15da3166-5087-11e5-9446-92d863892be5.jpg)

**Comment by dragthor** [comment]
Do you have a quick Js Fiddle?

**Comment by sebastiansulinski** [comment]
Afraid not - replaced the plugin with a different one.

**Comment by ahebrank** [comment]
From my note on http://foundation.zurb.com/forum/posts/24414-offcanvas-not-working-in-ie11

In the F5 [off-canvas documentation](http://foundation.zurb.com/sites/docs/v/5.5.3/components/offcanvas.html#inner-wrap), they use a `<main>` semantic tag for the .inner-wrap container.  The problem is [IE11 doesn't fully support this tag](http://caniuse.com/#feat=html5semantic) (see note 2), so the fix is to either use a `<div>` for this container or to add some reset styling to `<main>`:

``` css
main { display: block; }
 ```
