### ISSUE TITLE
How to create a master-detail view using foundation?

### ISSUE THREAD

**Issue by opensourcegeek** [zurb/foundation#6874]
I'm quite new to foundation, I quite like the data-interchange idea to target partials for different screen sizes. I'm trying to understand what components to use to make a master-detail screen where the detail screen appears on anything bigger than medium screens but hides the detail view on smaller screens. However the user must be able to click on an item in the master view to get to the detail view. Can I use data-interchange idea to achieve that? Is there any relevant tutorials/documentation that covers this idea?

**Comment by rafibomb** [comment]
The Foundation forum would be a great place to seek some help with troubleshooting what might be going on here. If it turns out to be a defect, you'll have some more info to provide here which will help prioritize and get it fixed.

We're trying to keep the issue list focused on confirmed defects in Foundation, so any help everyone can provide to differentiate between usage / troubleshooting and actual defects is appreciated!
