### ISSUE TITLE
What date to next release ?

### ISSUE THREAD

**Issue by jonatasfreitasv** [zurb/foundation#6900]
I send pull request (is marged) fixing many bugs and this not go to actual release, what date to next release ?

**Comment by rafibomb** [comment]
There will still be lots of people using Foundation 5 even after Foundation 6 launches because they already built or started building on 5. So any PR's for 5 will still be valuable for lots of people.

Foundation for Sites 6 is a new codebase with many updates. We're doing a private release now and will announce the release date soon.
