### ISSUE TITLE
iOS udpate 9.0.2 Mobile nav (topbar) no longer works right

### ISSUE THREAD

**Issue by estockwellalpert** [zurb/foundation#6926]
I just updated iOS on my phone to the latest version, and the topbar no longer works right. The sliding functionality of the menu now causes the body to shrink to accommodate the width of the submenu, which starts fully to the right of the body and slides over the body; rather than sliding in from the edge of the screen, the body shrinks to show the entire content.

The relevant script is foundation.topbar.js, it seems to be this line that is causing it:

    section.css({ left: -(100 * topbar.data('index')) + '%' });

You can view my site at uat.msdonline.com to see the problem. I've attached screenshots of the issue
![menu](https://cloud.githubusercontent.com/assets/7767565/10378591/bf7db752-6dd7-11e5-84e3-531a77cc6cc9.png)
![menu2](https://cloud.githubusercontent.com/assets/7767565/10378589/bf7c56c8-6dd7-11e5-8565-5b10a22d6efd.png)
![menu3](https://cloud.githubusercontent.com/assets/7767565/10378590/bf7cdb02-6dd7-11e5-9076-c51a2a3278bf.png)

**Comment by rafibomb** [comment]
Hmmm, that's weird. Can't replicate this on the docs.

The <a href="http://foundation.zurb.com/forum/">Foundation forum</a> would be a great place to seek some help with troubleshooting what might be going on here. If it turns out to be a defect, you'll have some more info to provide here which will help prioritize and get it fixed.

We're trying to keep the issue list focused on confirmed defects in Foundation, so any help everyone can provide to differentiate between usage / troubleshooting and actual defects is appreciated!
