### ISSUE TITLE
Cannot change top-bar bg color

### ISSUE THREAD

**Issue by SylarRuby** [zurb/foundation#6948]
I have managed to change the navbar color but I cant change the bg hover for `<ul class="title-area">`. Where is that???

**Comment by thiagotomasi** [comment]
@SylarRuby Foundation don't have a rule for that, you need to create, somethig like this:
```
.title-area:hover {
    background-color: red; // add the color you want
}
``` 
Is this your doubt?

**Comment by SylarRuby** [comment]
I've added that into a custom.css and it's still back ($oil) when hovered. Ive change the rest of the navbar but `.title-area:hover` is still black.

**Comment by thiagotomasi** [comment]
@SylarRuby could you post a `codepen` or a `jsfiddle` with this code please!

**Comment by SylarRuby** [comment]
Its just this:

<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to 'Demo', root_path %></h1>
    </li>
</nav>

**Comment by thiagotomasi** [comment]
@SylarRuby your code is good, and the example I showed to you should works.
But I need to see how your code HTML is interpreting your CSS, could you show me?
This way I can help you!

**Comment by rafibomb** [comment]
The <a href=“http://foundation.zurb.com/forum/”>Foundation forum</a> would be a great place to seek some help with troubleshooting what might be going on here. If it turns out to be a defect, you'll have some more info to provide here which will help prioritize and get it fixed.

We're trying to keep the issue list focused on confirmed defects in Foundation, so any help everyone can provide to differentiate between usage / troubleshooting and actual defects is appreciated!
