### ISSUE TITLE
How to generate scss/foundation/_settings.scss

### ISSUE THREAD

**Issue by klierik** [zurb/foundation#6951]
Good day.
This is not issue but i don't found other way to contact with you (

Can you tell me please how do you generate file `https://github.com/zurb/foundation/blob/master/scss/foundation/_settings.scss` ?

Or you fill it manually?

Thanks a lot

**Comment by jgacuca567** [comment]
@klierik , your _settings.scss should compile in your app.scss once you run grunt. You can then change the variables manually in the settings.scss file

**Comment by klierik** [comment]
@jgacuca567 thanks you for reply.

but i'm ask about other...
how do you create `_settings.scss`? What do you use for concat variables from other `*.scss` files and save it into `_settings.scss`?

i have similar task... i have a lot of `*.scss` files with variables and i need assemble all `$variables` into one file, like `_settings.scss`

Thanks

**Comment by jgacuca567** [comment]
@klierik is it possible for you to post an example of the pages screnshot then I can know like what you want to do .

**Comment by klierik** [comment]
for example some sass files that i have:
http://take.ms/MKz4X
http://take.ms/I7yBz
http://take.ms/LwcQd

So at the beginning of each .scss file i have some individual $variables. Now i need collect all $variables in `_settings.scss` file (like you do that).

I don't found any grunt plugin for this :( But i found your `_settings.scss` file and i suppose you generate it with some tool (not manually) ?!

**Comment by jgacuca567** [comment]
For that question to gather them in one file, I don't know best option is ask either @rafibomb . He would know.

**Comment by rafibomb** [comment]
The <a href="http://foundation.zurb.com/forum">Foundation forum</a> would be a great place to seek some help with troubleshooting what might be going on here. If it turns out to be a defect, you'll have some more info to provide here which will help prioritize and get it fixed.

We're trying to keep the issue list focused on confirmed defects in Foundation, so any help everyone can provide to differentiate between usage / troubleshooting and actual defects is appreciated!
