### ISSUE TITLE
Reveal modal sizing on medium devices is abnormally small?

### ISSUE THREAD

**Issue by nicatronTg** [zurb/foundation#6962]
Maybe this is the correct sizing after all, but I was hoping someone had a good solution (like making medium devices scale reveal modals to full size). As you can see, this "tiny" reveal modal is very, very thin on an iPad Mini. On a desktop PC, it looks fine, and on a phone, the modal occupies the entire screen (and thus, the problem doesn't occur). This only happens on the "medium" screen variant.

![image-1](https://cloud.githubusercontent.com/assets/532647/10747488/567782e0-7c1b-11e5-81a5-d1094f8ebcf6.png)

**Comment by rafibomb** [comment]
The <a href=“http://foundation.zurb.com/forum/”>Foundation forum</a> would be a great place to seek some help with troubleshooting what might be going on here. If it turns out to be a defect, you'll have some more info to provide here which will help prioritize and get it fixed.

We're trying to keep the issue list focused on confirmed defects in Foundation, so any help everyone can provide to differentiate between usage / troubleshooting and actual defects is appreciated!

**Comment by nicatronTg** [comment]
@rafibomb perhaps it would be pertinent to place that in the readme or in the contributing file, which is linked to when creating an issue.
