### ISSUE TITLE
Customize max-width of screen for toggling mobile version of top-bar on

### ISSUE THREAD

**Issue by a7mad-12** [zurb/foundation#6984]
Hi, where in foundation .css file can i change the required width for displaying mobile version of top-bar ?! it's already set to it's default value (40em) and I want to change this value.

**Comment by rafibomb** [comment]
The <a href=“http://foundation.zurb.com/forum/

”>Foundation forum</a> would be a great place to seek some help with troubleshooting what might be going on here. If it turns out to be a defect, you'll have some more info to provide here which will help prioritize and get it fixed.

We're trying to keep the issue list focused on confirmed defects in Foundation, so any help everyone can provide to differentiate between usage / troubleshooting and actual defects is appreciated!
